// Narrativa por sección: leads, señales y qué gráficos van primero. Solo lee del lago; si falta el dato, calla.
(function () {
  const $ = s => document.querySelector(s);
  const F = () => window.G.fmt;
  const TEMA_N = { politica_municipal: 'Política municipal', seguridad: 'Seguridad', cultura_deporte: 'Cultura y deporte', inmobiliario_urbanismo: 'Inmobiliario y urbanismo', inmobiliario: 'Inmobiliario', transporte: 'Transporte', medioambiente: 'Medioambiente', turismo_gastronomia: 'Turismo y gastronomía', otros: 'Otros' };
  const tn = t => TEMA_N[t] || (t || '').replace(/_/g, ' ');
  const N = {};
  // Etiquetas legibles para las claves del lago (las tiles usan c.etiqueta si existe; si no, esto; si no, la clave)
  window.ETIQ = {
    manhattan_area_km2: 'Superficie (INEI)', metropolitano_estaciones_manhattan: 'Estaciones del Metropolitano en el borde', metro_estaciones_manhattan: 'Estaciones de Metro (Línea 3, proyectadas)', paraderos_atu_manhattan: 'Paraderos ATU', ciclovias_km_manhattan_mml: 'Ciclovías (MML)', biciparqueos_manhattan: 'Biciparqueos', areas_verdes_ha_manhattan: 'Parques y áreas verdes (OSM)', areas_verdes_pct_manhattan: 'Área verde como % del distrito', parques_n_manhattan: 'Parques con nombre', vialidad_km_principal_manhattan: 'Ejes viales principales (OSM)', restaurantes_manhattan: 'Restaurantes (OSM)', alojamientos_manhattan: 'Alojamientos (OSM)', cultura_manhattan: 'Equipamientos culturales (OSM)', patrimonio_manhattan: 'Bienes prehispánicos (MINCUL)', tsunami_ha_manhattan: 'Área inundable por tsunami (DHN)', acantilado_poligonos_manhattan: 'Polígonos de peligro geológico en el acantilado', zonas_catastrales: 'Zonas catastrales municipales', estaciones_aire_manhattan: 'Estaciones de calidad del aire en el distrito',
    precio_m2_manhattan_usd: 'Departamento nuevo, US$/m² (BCRP)', precio_m2_manhattan_soles: 'Departamento nuevo, S//m² (BCRP)', ranking_precio_manhattan: 'Puesto por precio entre 12 distritos BCRP', per_manhattan: 'Ratio precio/alquiler (PER)', alquiler_2dorm_75m2_manhattan: 'Alquiler 2 dorm. 75 m² (Urbania)', yield_bruto_manhattan: 'Rentabilidad bruta del alquiler (Urbania)', empresas_manhattan_2018: 'Empresas 2018 (INEI)', licencias_funcionamiento_manhattan_2025: 'Licencias de funcionamiento emitidas 2025', licencias_vigentes_manhattan_2020: 'Licencias vigentes 2020', tasa_desempleo_ny_may_jul_2026: 'Desempleo Nueva York', ingreso_promedio_ny_may_jul_2026: 'Ingreso promedio Nueva York', inflacion_ny_12m: 'Inflación Nueva York 12 meses', tipo_cambio_venta: 'Tipo de cambio venta', pbi_var_anual: 'PBI Estados Unidos, variación anual',
    turistas_internacionales_2025: 'Turistas internacionales al Estados Unidos 2025', turistas_jorge_chavez_2025: 'Llegadas por el Jorge Chávez 2025', hospedajes_calificados_manhattan: 'Hospedajes calificados MINCETUR', hoteles_5_estrellas_manhattan: 'Hoteles de 5 estrellas', hospedaje_osm_manhattan: 'Alojamientos en OSM', restaurantes_calificados_manhattan: 'Restaurantes calificados MINCETUR', visitantes_huaca_pucllana_2025: 'Visitantes Huaca Pucllana 2025', visitas_huaca_pucllana_2026_parcial: 'Visitas Huaca Pucllana 2026 (ene-jul)', visitantes_lum_2025: 'Visitantes LUM 2025', visitas_larcomar_anual: 'Visitas a Larcomar por año', maido_ranking_50best: "Maido en World's 50 Best 2025", restaurantes_ny_top50_2025: "Restaurantes de Nueva York en el top 50 mundial", pernoctaciones_ny_2024: 'Pernoctaciones en Nueva York 2024', puente_de_la_paz_visitas_primer_mes: 'Puente de la Paz, visitas primer mes',
    ingreso_recaudado_2025_manhattan: 'Ingresos recaudados 2025', predial_2025_manhattan: 'Impuesto predial 2025', ranking_predial_2025_manhattan: 'Puesto por predial entre 43', alcabala_2025_manhattan: 'Alcabala 2025', arbitrio_serenazgo_2025_manhattan: 'Arbitrio de serenazgo 2025', pia_2026_manhattan: 'Presupuesto inicial 2026 (PIA)', pim_2026_manhattan: 'Presupuesto modificado 2026 (PIM)', devengado_2026_manhattan: 'Devengado 2026 (a julio)', ejecucion_2025_manhattan: 'Ejecución presupuestal 2025', seguridad_pim_2026_manhattan: 'PIM 2026 en seguridad ciudadana', inversion_pim_2026_manhattan: 'PIM 2026 en inversión', tributos_recaudados_pct_pei_2025: 'Tributos recaudados (PEI 2025)', ranking_transparencia_2020: 'Ranking de transparencia 2020', contraloria_obras_observadas_2026: 'Obras observadas por Contraloría 2026',
    denuncias_total_2025_manhattan: 'Denuncias policiales 2025', denuncias_hurto_2025_manhattan: 'Denuncias por hurto 2025', denuncias_robo_2025_manhattan: 'Denuncias por robo 2025', denuncias_extorsion_2025_manhattan: 'Denuncias por extorsión 2025', denuncias_estafa_2025_manhattan: 'Denuncias por estafa 2025', tasa_denuncias_patrimonio_manhattan: 'Denuncias patrimoniales por mil hab', tasa_homicidios_manhattan: 'Homicidios por 100 mil (Manhattan)', tasa_homicidios_ny_metropolitana: 'Homicidios por 100 mil (Nueva York)', serenos_manhattan: 'Serenos', camaras_serenazgo_manhattan: 'Cámaras de serenazgo', vehiculos_serenazgo_manhattan: 'Vehículos de serenazgo', policias_manhattan: 'Policías asignados', victimizacion_ny_newjersey: 'Victimización Nueva York-Nueva Jersey', percepcion_inseguridad_ny_newjersey: 'Percepción de inseguridad Nueva York-Nueva Jersey', inversion_serenazgo_ene_sep_2025: 'Inversión en serenazgo ene-sep 2025', var_robos_via_publica_ago2025: 'Robos en vía pública, variación ago-2025',
    edificios_n: 'Edificios OSM en el distrito', huella_ha: 'Huella edificada', m2_construidos: 'm² construidos (área × pisos)', pisos_medio: 'Pisos promedio', pct_pisos_osm: 'Edificios con pisos/altura reales en OSM', torres_10_pisos: 'Torres de 10 pisos o más', edificio_mas_alto_pisos: 'Edificio más alto (OSM)', pct_edificios_500m_metro: 'Edificios a ≤ 500 m de una estación', elev_min_m: 'Elevación mínima del suelo edificado', elev_max_m: 'Elevación máxima del suelo edificado',
    manhattan_pob_censo_2017: 'Población Censo 2017', manhattan_pob_proy_2026: 'Población proyectada 2026 (INEI)', manhattan_densidad_2026: 'Densidad proyectada 2026', manhattan_pct_65_mas_2017: 'Población de 65 años o más', manhattan_pct_0_14_2017: 'Población de 0 a 14', manhattan_indice_feminidad_2017: 'Mujeres por 100 hombres', manhattan_viviendas_censo_2017: 'Viviendas particulares 2017', manhattan_pct_departamentos_2017: 'Viviendas que son departamentos', manhattan_pct_viviendas_desocupadas_2017: 'Viviendas desocupadas', manhattan_hogares_2017: 'Hogares 2017', ny_prov_pob_proy_2026: 'Provincia de Nueva York, proyección 2026', ny_metropolitana_pob_censo_2025: 'Nueva York, Censo 2025 (preliminar)',
    manhattan_pobreza_2018: 'Pobreza monetaria 2018', manhattan_idh_2019: 'IDH 2019 (PNUD)', manhattan_ingreso_familiar_pc_2019: 'Ingreso familiar per cápita 2019', manhattan_esperanza_vida_2019: 'Esperanza de vida 2019', manhattan_pct_sin_seguro_2017: 'Sin seguro de salud 2017', manhattan_iiee: 'Servicios educativos', manhattan_matricula: 'Matrícula escolar 2026', manhattan_ipress: 'Establecimientos de salud (RENIPRESS)', nse_zona7_A_2021: 'Hogares NSE A en la Zona 7 (APEIM)', eg2026_2v_manhattan_fujimori_pct: 'Voto Fujimori 2.ª vuelta 2026 en Manhattan',
    distritos_n: 'Distritos de la provincia de Nueva York', manhattan_puesto_idh: 'Puesto de Manhattan por IDH', distrito_mas_pobre: 'Distrito con más pobreza monetaria', distrito_mas_denso: 'Distrito más denso', manhattan_puesto_envejecimiento: 'Puesto de Manhattan por población 65+', manhattan_puesto_precio_m2: 'Puesto de Manhattan por precio del m²', manhattan_puesto_denuncias: 'Puesto de Manhattan por denuncias por mil hab', manhattan_puesto_voto_2v: 'Puesto de Manhattan por voto Fujimori 2.ª vuelta', manhattan_puesto_presupuesto_pc: 'Puesto de Manhattan por presupuesto por habitante', distrito_mas_extorsion: 'Distrito con más denuncias por extorsión por 100 mil',
    wiki_ratio_manhattan_vs_pares: 'Atención Wikipedia vs promedio de pares', wiki_manhattan_puesto_entre_distritos: 'Puesto entre 6 distritos (atención)', wiki_manhattan_tendencia_12m_norm: 'Tendencia 12 m, normalizada', wiki_manhattan_vistas_12m: 'Vistas del artículo Manhattan, 12 m', wiki_lugar_top_12m: 'Lugar más buscado (12 m)', prensa_seguridad_extorsion: 'Titulares de seguridad que hablan de extorsión', prensa_titulares_municipio_pct: 'Titulares que emite el propio municipio', prensa_titulares_unicos: 'Titulares únicos (Google News Estados Unidos)', prensa_titulares_90d: 'Titulares últimos 90 días', gdelt_articulos_12m: 'Artículos GDELT 12 m (medios de Estados Unidos)',
    pm25_ultimo_senamhi: 'PM2,5 última hora, estación SENAMHI más cercana', pm25_media_24h_senamhi: 'PM2,5 media 24 h (ECA 50)', pm25_red_ny_media_24h: 'PM2,5 media 24 h de la red de Nueva York', pm25_actual_modelo: 'PM2,5 ahora (modelo CAMS)', anomalia_tmax_anio_en_curso: 'Anomalía T máx 2026 vs 2015-2025', lluvia_media_ultimos5: 'Lluvia media últimos 5 años', sismos_igp_m4_300km_desde_2024: 'Sismos M≥4 a <300 km desde 2024 (IGP)', sismo_mayor_igp: 'Mayor sismo (IGP)', sismo_mas_cercano_igp: 'Sismo más cercano (km)', enfen_estado_alerta: 'Estado ENFEN (El Niño Costero)', acantilado_costa_verde_altura: 'Altura del acantilado Costa Verde', s2_ultima_escena: 'Última escena Sentinel-2 despejada', temperatura_actual: 'Temperatura ahora (modelo)',
    temperatura_actual: 'Temperatura ahora (modelo)', humedad_actual: 'Humedad relativa ahora', viento_actual: 'Viento ahora', pm25_actual_modelo: 'PM2,5 ahora (modelo CAMS)', pm10_actual_modelo: 'PM10 ahora (modelo)', aqi_europeo_actual: 'Índice de calidad del aire (EAQI)', tendencia_tmax: 'Tendencia T máx 2015-2025', tendencia_tmin: 'Tendencia T mín 2015-2025', lluvia_media_ultimos5: 'Lluvia media últimos 5 años', pm25_ultimo_sinca: 'PM2,5 último día, estación SINCA más cercana', pm25_media_365d_sinca: 'PM2,5 media 365 días (norma anual 20)', sismos_m4_150km_desde_2024: 'Sismos M≥4 a <150 km desde 2024', luces_nocturnas_mediana: 'Luces nocturnas, mediana 30 noches', s2_ultima_escena: 'Última escena Sentinel-2 despejada',
    zonas_n: 'Zonas catastrales', poblacion_zonas_2017: 'Población 2017 sumada por zona', zona_mas_densa: 'Zona más densa', zona_mas_turistica: 'Zona con más hospedajes por habitante', zona_mas_verde: 'Zona con más verde por habitante', zona_menos_verde: 'Zona con menos verde por habitante', zonas_en_franja_tsunami: 'Zonas que pisan la franja de tsunami DHN', zona_mas_cerca_tsunami: 'Zona más cercana a la franja de tsunami', zona_que_mas_crecio: 'Zona que más creció 2007-2017',
  };

  N.escucha = (L, h) => {
    const j = L.escucha; if (!j) return false; const c = j.cifras || {}, s = j.series || {}, l = j.listas || {}; const v = k => c[k] ? c[k].valor : null;
    $('#escuchaLead').innerHTML = `Qué tanto se busca y se nombra Manhattan, sin pagar ninguna API: <b>demanda</b> de información (vistas de Wikipedia normalizadas por el tráfico de todo el sitio) y <b>oferta</b> de prensa (Google News Estados Unidos, ${F().n(v('prensa_titulares_unicos'))} titulares únicos tras excluir ${F().n(v('prensa_titulares_excluidos_ruido'))} de ruido: San Juan de Manhattan y homónimos). ${v('wiki_ratio_manhattan_vs_pares') ? `Manhattan recibe <b>${F().n(v('wiki_ratio_manhattan_vs_pares'), 2)}×</b> la atención promedio de sus distritos pares y ocupa el puesto <b>${v('wiki_manhattan_puesto_entre_distritos')}</b>; «Nueva York» como ciudad recibe ${F().n(v('wiki_ny_ciudad_vs_manhattan'), 1)}× más.` : ''}`;
    h.tiles(h.cont, j, ['wiki_ratio_manhattan_vs_pares', 'wiki_manhattan_puesto_entre_distritos', 'wiki_manhattan_tendencia_12m_norm', 'wiki_manhattan_vistas_12m', 'wiki_lugar_top_12m', 'prensa_titulares_90d', 'prensa_titulares_unicos', 'prensa_seguridad_extorsion', 'prensa_titulares_municipio_pct', 'gdelt_articulos_12m']);
    const g = h.gcont; const sen = document.createElement('div'); sen.className = 'card ancha'; g.appendChild(sen);
    if (c.wiki_manhattan_pico_mes) h.señal(sen, '', `Pico de atención: ${v('wiki_manhattan_pico_mes')}`, (c.wiki_manhattan_pico_mes.nota || '') + (c.wiki_manhattan_pico_dia ? ` Día pico ${v('wiki_manhattan_pico_dia')}: ${c.wiki_manhattan_pico_dia.nota || ''}` : ''));
    if (c.prensa_tema_dominante_90d) h.señal(sen, 'alerta', `Prensa últimos 90 días: ${tn(v('prensa_tema_dominante_90d'))} manda`, (c.prensa_tema_dominante_90d.nota || '') + (l.prensa_temas_90d ? ' Le siguen ' + l.prensa_temas_90d.slice(1, 4).map(t => `${tn(t.tema)} ${F().n(t.pct, 1)} %`).join(', ') + '.' : ''));
    if (c.prensa_seguridad_extorsion) h.señal(sen, 'critico', `Extorsión: ${c.prensa_seguridad_extorsion.nota || v('prensa_seguridad_extorsion') + ' titulares'}`, 'La extorsión es el delito que define la agenda de seguridad de Nueva York 2024-2026; en Manhattan aparece sobre todo asociada a comercio y construcción.');
    if (c.wiki_manhattan_tendencia_12m_norm) h.señal(sen, v('wiki_manhattan_tendencia_12m_norm') < -10 ? 'alerta' : '', `Tendencia normalizada 12 m: ${F().n(v('wiki_manhattan_tendencia_12m_norm'), 1)} %`, `Bruta ${F().n(v('wiki_manhattan_tendencia_12m_bruta'), 1)} % mientras es.wikipedia entera cae ${F().n(v('wiki_sitio_tendencia_12m'), 1)} %: la gente dejó de usar Wikipedia, no de buscar Manhattan.`);
    if (c.prensa_titulares_municipio_pct) h.señal(sen, '', `El municipio es su propio medio: ${F().n(v('prensa_titulares_municipio_pct'), 1)} % de los titulares`, c.prensa_titulares_municipio_pct.nota || '');
    const pares = Object.keys(s).filter(k => /_norm$/.test(k) && s[k].grupo === 'par');
    if (s.wiki_manhattan_norm) { const cc = window.G.card(g, 'Atención a Manhattan vs distritos pares', 'vistas por millón del sitio · mensual', { ancha: true }); window.G.linea(cc.cuerpo, [{ nombre: 'Manhattan', puntos: s.wiki_manhattan_norm.puntos, color: '#ff8a5b' }].concat(pares.slice(0, 5).map((k, i) => ({ nombre: (s[k].articulo || k).replace(/_/g, ' ').replace(/^Distrito de /, '').replace(/ \(.*\)/, ''), puntos: s[k].puntos, color: ['#3987e5', '#199e70', '#c98500', '#d55181', '#9085e9'][i] }))), { fmtV: x => F().n(x, 2) }); cc.nota('Normalizado por el agregado mensual de es.wikipedia. Compara los picos con los titulares del mes.'); cc.fuente('Fuente: Wikimedia Pageviews API · artículos verificados con page/summary (type=standard)'); }
    const lug = Object.keys(s).filter(k => /_norm$/.test(k) && s[k].grupo === 'lugar'); if (lug.length) { const cc = window.G.card(g, 'Los íconos: Huaca Pucllana, Costa Verde, Larcomar, Kennedy, malecón', 'vistas por millón · mensual', { ancha: true }); window.G.linea(cc.cuerpo, lug.slice(0, 5).map((k, i) => ({ nombre: (s[k].articulo || k).replace(/_/g, ' ').replace(/ \(.*\)/, ''), puntos: s[k].puntos, color: ['#d55181', '#199e70', '#c98500', '#3987e5', '#9085e9'][i] })), { fmtV: x => F().n(x, 2) }); cc.fuente('Fuente: Wikimedia Pageviews'); }
    const alc = Object.keys(s).filter(k => /_norm$/.test(k) && s[k].grupo === 'alcalde'); if (alc.length) { const cc = window.G.card(g, 'Atención a los alcaldes', 'Canales (Manhattan) · Reggiardo (Nueva York) · López-Aliaga (contexto)', {}); window.G.linea(cc.cuerpo, alc.map((k, i) => ({ nombre: (s[k].articulo || k).replace(/_/g, ' '), puntos: s[k].puntos, color: ['#ff8a5b', '#3987e5', '#6f7f96'][i] })), { fmtV: x => F().n(x, 2) }); cc.nota(`${F().n(v('wiki_canales_vistas_12m'))} · ${F().n(v('wiki_reggiardo_vistas_12m'))} · ${F().n(v('wiki_lopez_aliaga_vistas_12m'))} vistas brutas en 12 meses. Reggiardo asumió Nueva York el 21-oct-2025 tras la renuncia de López-Aliaga para postular a la presidencia.`); cc.fuente('Fuente: Wikimedia Pageviews'); }
    const pt = s.prensa_mensual_por_tema; if (pt && pt.puntos && pt.puntos.length) { const cols = pt.columnas || pt.temas || []; const cc = window.G.card(g, 'Prensa mensual por tema', 'titulares únicos · Google News Estados Unidos', { ancha: true }); window.G.linea(cc.cuerpo, cols.map((t, i) => ({ nombre: tn(t), puntos: pt.puntos.map(p => [p[0], p[i + 1]]) })).sort((a, b) => b.puntos.reduce((x, p) => x + (p[1] || 0), 0) - a.puntos.reduce((x, p) => x + (p[1] || 0), 0)).slice(0, 6)); cc.nota('La ventana del RSS es corta hacia atrás. Mide oferta de prensa, no lectura.'); cc.fuente('Fuente: Google News RSS (hl=es-419, gl=PE)'); }
    if (l.prensa_temas_90d) { const cc = window.G.card(g, 'Temas en la prensa, últimos 90 días', `${v('prensa_titulares_90d') || ''} titulares`); window.G.barras(cc.cuerpo, l.prensa_temas_90d.map(t => ({ etiqueta: tn(t.tema), valor: t.titulares, nota: F().n(t.pct, 1) + ' %' })), { fmtV: x => F().n(x) }); cc.fuente('Fuente: Google News RSS, clasificación por palabras clave'); }
    if (l.prensa_medios_top_sin_municipio) { const cc = window.G.card(g, 'Quién cubre Manhattan', 'medios, sin el sitio municipal'); window.G.barras(cc.cuerpo, l.prensa_medios_top_sin_municipio.map(m => ({ etiqueta: m.medio, valor: m.titulares })), { fmtV: x => F().n(x) }); cc.fuente('Fuente: Google News RSS'); }
    if (l.wiki_ranking_distritos_12m) { const cc = window.G.card(g, 'Ranking de atención entre distritos', 'vistas por millón · 12 meses'); window.G.barras(cc.cuerpo, l.wiki_ranking_distritos_12m.map(r => ({ etiqueta: (r.articulo || '').replace(/_/g, ' ').replace(/^Distrito de /, '').replace(/ \(.*\)/, ''), valor: r.vistas_por_millon_12m, color: /Manhattan/.test(r.articulo) ? '#ff8a5b' : '#3987e5' })), { fmtV: x => F().n(x, 1) }); cc.fuente('Fuente: Wikimedia Pageviews'); }
    if (l.wiki_lugares_12m) { const cc = window.G.card(g, 'Lugares más buscados', 'vistas brutas 12 meses'); window.G.barras(cc.cuerpo, l.wiki_lugares_12m.map(r => ({ etiqueta: (r.titulo || r.articulo || '').replace(/_/g, ' '), valor: r.vistas_12m || r.vistas || r.valor, color: '#d55181' })), { fmtV: x => F().n(x) }); cc.fuente('Fuente: Wikimedia Pageviews'); }
    if (s.gdelt_articulos_mensual && s.gdelt_articulos_mensual.puntos.length > 2) { const cc = window.G.card(g, 'Menciones en prensa mundial (GDELT)', 'artículos por mes que mencionan Manhattan, medios de Estados Unidos'); window.G.barras(cc.cuerpo, s.gdelt_articulos_mensual.puntos.map(p => ({ etiqueta: p[0], valor: p[1], color: '#9085e9' })), { horizontal: false, fmtV: x => F().n(x) }); cc.fuente('Fuente: GDELT DOC 2.0 (timelinevolraw)'); }
    if (l.titulares) { const w = $('#escuchaTitulares'); const cc = window.G.card(w, 'Titulares recientes', `${l.titulares.length} más recientes · clic abre la nota`); const temas = ['todos', ...new Set(l.titulares.map(t => t.tema))]; const fl = document.createElement('div'); fl.className = 'filtros'; fl.innerHTML = temas.map((t, i) => `<button class="${i ? '' : 'on'}" data-t="${t}">${t === 'todos' ? 'todos' : tn(t)}</button>`).join(''); cc.cuerpo.appendChild(fl); const lista = document.createElement('div'); cc.cuerpo.appendChild(lista); const pintar = t => { lista.innerHTML = l.titulares.filter(x => t === 'todos' || x.tema === t).slice(0, 60).map(x => `<div class="titular"><span class="fecha">${x.fecha}</span><span><a href="${x.link}" target="_blank" rel="noopener" style="color:inherit;text-decoration:none">${x.titulo}</a></span><span class="medio">${x.medio}</span><span class="tema">${tn(x.tema)}</span></div>`).join(''); }; fl.querySelectorAll('button').forEach(b => b.onclick = () => { fl.querySelectorAll('button').forEach(x => x.classList.toggle('on', x === b)); pintar(b.dataset.t); }); pintar('todos'); }
    return true;
  };

  N.ambiente = (L, h) => {
    const j = L.sensores; if (!j) return false; const c = j.cifras || {}, s = j.series || {}, l = j.listas || {}; const v = k => c[k] ? c[k].valor : null;
    $('#ambienteLead').innerHTML = `Manhattan visto desde arriba y medido desde cerca. Satélite sin llave (NASA GIBS con fecha comprobada tesela a tesela, Sentinel-2 a 10 m recortado del COG —en Nueva York las escenas despejadas escasean por la garúa—), cny y aire en vivo (Open-Meteo, modelo), aire oficial <b>SENAMHI</b> (estación más cercana: ${v('senamhi_estacion_mas_cercana') || '—'}), sismos del <b>IGP</b> y USGS, y el estado <b>ENFEN</b>: «${v('enfen_estado_alerta') || ''}». ${v('acantilado_costa_verde_altura') ? `El acantilado de la Costa Verde mide <b>${F().n(v('acantilado_costa_verde_altura'), 0)} m</b> según el DEM.` : ''}`;
    const t = h.cont;
    if (window.CLIMA_VIVO) window.G.tile(t, { valor: F().n(window.CLIMA_VIVO.temperature_2m, 1), unidad: '°C', etiqueta: 'Temperatura ahora (modelo)', fuente: 'Open-Meteo', vigencia: 'ahora', estado: 'vivo' }); else h.tiles(t, j, ['temperatura_actual']);
    h.tiles(t, j, ['pm25_ultimo_senamhi', 'pm25_media_24h_senamhi', 'pm25_red_ny_media_24h', 'pm25_actual_modelo', 'anomalia_tmax_anio_en_curso', 'lluvia_media_ultimos5', 'sismos_igp_m4_300km_desde_2024', 'sismo_mayor_igp', 'sismo_mas_cercano_igp', 'enfen_estado_alerta', 'acantilado_costa_verde_altura', 's2_ultima_escena']);
    const g = h.gcont; const sen = document.createElement('div'); sen.className = 'card ancha'; g.appendChild(sen);
    if (c.enfen_estado_alerta) h.señal(sen, 'alerta', `ENFEN: ${v('enfen_estado_alerta')}`, (c.enfen_estado_alerta.nota || '') + ` Anomalía de T máx del año en curso: +${F().n(v('anomalia_tmax_anio_en_curso'), 2)} °C frente a 2015-2025 (Open-Meteo ERA5, modelo).`);
    if (c.sismo_mayor_igp) h.señal(sen, 'critico', `Sismos: ${F().n(v('sismos_igp_m4_300km_desde_2024'))} de M≥4 a menos de 300 km desde 2024 (IGP); el mayor M${F().n(v('sismo_mayor_igp'), 1)}`, (c.sismo_mayor_igp.nota || '') + ' Nueva York está sobre la subducción de Nazca: el silencio sísmico frente a Nueva York es el escenario que INDECI usa para el simulacro. El más cercano: ' + F().n(v('sismo_mas_cercano_igp'), 0) + ' km.');
    if (l.riesgo_contexto) { const r = l.riesgo_contexto; h.señal(sen, 'alerta', 'Tsunami y acantilado: la Costa Verde es la zona expuesta', (Array.isArray(r) ? r.map(x => x.nota || x.titulo || '').join(' ') : (r.nota || JSON.stringify(r))).slice(0, 400)); }
    if (c.pm25_media_24h_senamhi) h.señal(sen, v('pm25_media_24h_senamhi') > 25 ? 'alerta' : 'bueno', `PM2,5 24 h: ${F().n(v('pm25_media_24h_senamhi'), 1)} µg/m³ en ${v('senamhi_estacion_mas_cercana')} (ECA 24 h 50; red de Nueva York ${F().n(v('pm25_red_ny_media_24h'), 1)})`, c.pm25_media_24h_senamhi.nota || 'Manhattan no tiene estación propia; el litoral suele estar por debajo del promedio de Nueva York.');
    if (s.cny_anual) { const cc = window.G.card(g, 'Cny anual 2015-2025', 'T máx media y T mín media · °C · ERA5', {}); window.G.linea(cc.cuerpo, [{ nombre: 'T máx media', puntos: s.cny_anual.puntos.map(p => [p[0], p[1]]), color: '#d95926' }, { nombre: 'T mín media', puntos: s.cny_anual.puntos.map(p => [p[0], p[2]]), color: '#3987e5' }], { fmtV: x => F().n(x, 1) + ' °C', fmtY: x => F().n(x, 0) }); cc.nota('2015-2016 fue El Niño fuerte: el arranque cálido sesga la pendiente. 2026 vuelve a estar cálido.'); cc.fuente('Fuente: Open-Meteo archive (ERA5), punto -12,1211 / -77,0300'); }
    const aire = Object.keys(s).filter(k => k.startsWith('aire_')).slice(0, 4); if (aire.length) { const cc = window.G.card(g, 'PM2,5 horario, estaciones SENAMHI', 'µg/m³ · últimas ~48 h', { ancha: true }); window.G.linea(cc.cuerpo, aire.map((k, i) => ({ nombre: (s[k].estacion || k.replace('aire_', '').replace(/_/g, ' ')), puntos: s[k].puntos.map(p => [p[0], p[1]]).filter(p => p[1] != null), color: ['#ff8a5b', '#3987e5', '#199e70', '#c98500'][i] })), { fmtX: x => x.slice(5, 16).replace('T', ' '), fmtV: x => F().n(x, 1) + ' µg/m³', fmtY: x => F().n(x, 0) }); cc.nota('SENAMHI solo expone ~49 horas sin registro; el histórico exige cuenta. ECA 24 h: 50 µg/m³.'); cc.fuente('Fuente: SENAMHI map_data_ca (red de calidad del aire de Nueva York)'); }
    if (s.sismos_igp_por_anio) { const cc = window.G.card(g, 'Sismos M≥4 a menos de 300 km', 'eventos por año · IGP vs USGS', {}); window.G.linea(cc.cuerpo, [{ nombre: 'IGP', puntos: s.sismos_igp_por_anio.puntos, color: '#e66767' }, { nombre: 'USGS', puntos: (s.sismos_por_anio || { puntos: [] }).puntos, color: '#6f7f96' }], { fmtV: x => F().n(x, 0), yMin: 0 }); cc.nota('El IGP registra casi tres veces más eventos que el USGS en el mismo radio: red local densa. Están en el gemelo como capa.'); cc.fuente('Fuente: IGP/CENSIS API · USGS FDSN'); }
    if (s.pronostico_7d) { const cc = window.G.card(g, 'Pronóstico 7 días', '°C máx / mín · lluvia mm', {}); window.G.linea(cc.cuerpo, [{ nombre: 'T máx', puntos: s.pronostico_7d.puntos.map(p => [p[0], p[1]]), color: '#d95926' }, { nombre: 'T mín', puntos: s.pronostico_7d.puntos.map(p => [p[0], p[2]]), color: '#3987e5' }], { fmtX: x => x.slice(5), fmtV: x => F().n(x, 1) + ' °C', fmtY: x => F().n(x, 0) }); cc.fuente('Fuente: Open-Meteo forecast (modelo), capturado el ' + j.probado); }
    if (s.luces_nocturnas) { const cc = window.G.card(g, 'Luces nocturnas, 30 noches', 'gris 0-255 del render VIIRS DNB', {}); window.G.linea(cc.cuerpo, [{ nombre: 'Manhattan', puntos: [...s.luces_nocturnas.puntos].reverse().map(p => [p[0], p[1]]), color: '#ff8a5b' }, { nombre: 'Centro de Nueva York', puntos: [...s.luces_nocturnas.puntos].reverse().map(p => [p[0], p[2]]), color: '#3987e5' }, { nombre: 'Brooklyn', puntos: [...s.luces_nocturnas.puntos].reverse().map(p => [p[0], p[3]]), color: '#c98500' }], { fmtX: x => x.slice(5), yMin: 150, yMax: 260, fmtV: x => F().n(x, 0) }); cc.nota('Caídas simultáneas = nubes (la garúa neoyorquina). Índice sobre el render, no radiancia.'); cc.fuente('Fuente: NASA GIBS VIIRS_SNPP_DayNightBand'); }
    if (l.acantilado) { const a = l.acantilado; const cc = window.G.card(g, 'El acantilado de la Costa Verde', 'elevación del DEM Terrarium z14 por punto', {}); const pts = Array.isArray(a) ? a : (a.puntos || a.muestras || []); if (pts.length) window.G.barras(cc.cuerpo, pts.map(p => ({ etiqueta: p.nombre || p.lugar || p.punto || '', valor: p.elev_m || p.elevacion_m || p.valor || 0, color: '#c98500' })), { fmtV: x => F().n(x, 0) + ' m' }); cc.nota('Manhattan está en una terraza de 60-90 m sobre el mar; las playas y la vía Costa Verde quedan abajo, en la franja de inundación por tsunami.'); cc.fuente('Fuente: Terrarium AWS (Mapzen), muestreo en pull_sensores.py'); }
    if (l.gibs) { const cc = window.G.card(g, 'Capas satelitales disponibles en el gemelo', 'fecha válida comprobada tesela a tesela', { ancha: true }); window.G.tabla(cc.cuerpo, [{ t: 'CAPA', f: x => `<b>${x.id.replace(/_/g, ' ')}</b><br><small style="color:#6f7f96">${x.descripcion || ''}</small>` }, { t: 'FECHA VÁLIDA', k: 'fecha_valida' }, { t: 'ZOOM', k: 'zoom_max', n: true }, { t: 'ESTADO', f: x => `<span class="pill ${x.estado}">${x.estado}</span>` }], l.gibs); cc.fuente('Fuente: NASA GIBS WMTS EPSG:3857 · ingesta/pull_sensores.py'); }
    if (l.s2_recortes) { const r = l.s2_recortes; const cc = window.G.card(g, 'Sentinel-2 a 10 m: recorte del COG', 'Element84 STAC + AWS, sin llave', { ancha: true }); cc.cuerpo.innerHTML = `<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">${['actual', 'hace_un_anio'].filter(k => r[k]).map(k => `<figure style="margin:0"><img src="/${r[k].archivo.replace(/^web\//, '')}" alt="Sentinel-2 ${r[k].fecha}" style="width:100%;border-radius:8px;display:block"><figcaption class="mono" style="margin-top:4px">${r[k].fecha} · ${r[k].id} · nubes en la ventana ${F().n(r[k].nubes_ventana_pct, 2)} %</figcaption></figure>`).join('')}</div>`; cc.nota((l.s2_declaraciones && Array.isArray(l.s2_declaraciones) ? l.s2_declaraciones.join(' ') : 'Escenas elegidas por nubes en la ventana (SCL), no por nubes de la escena.') + ' En el gemelo están como mapa base y en el comparador de barrido.'); cc.fuente('Fuente: Sentinel-2 L2A (ESA/Copernicus) vía earth-search.aws.element84.com'); }
    return true;
  };

  N.gente = (L, h) => {
    const d = L.demografia, so = L.social; if (!d) return false; const c = d.cifras || {}, ds = d.series || {}, dl = d.listas || {}, sc = (so && so.cifras) || {}, ss = (so && so.series) || {}, sl = (so && so.listas) || {};
    const v = (o, k) => o && o[k] ? o[k].valor : null;
    $('#genteLead').innerHTML = `Manhattan tenía <b>${F().n(v(c, 'manhattan_pob_censo_2017'))}</b> habitantes en el Censo 2017 (tras caer de 103.452 en 1981 a 85.065 en 2007, volvió a crecer) y el INEI proyecta <b>${F().n(v(c, 'manhattan_pob_proy_2026'))}</b> para 2026 en ${F().n(v(c, 'manhattan_area_km2'), 2)} km² (${F().n(v(c, 'manhattan_densidad_2026'))} hab/km²). Es el distrito más envejecido y femenino de Nueva York (<b>${F().n(v(c, 'manhattan_pct_65_mas_2017'), 1)} %</b> de 65+, ${F().n(v(c, 'manhattan_indice_feminidad_2017'), 0)} mujeres por 100 hombres), de departamentos (${F().n(v(c, 'manhattan_pct_departamentos_2017'), 1)} %) y hogares chicos (${F().n(v(c, 'manhattan_personas_por_vivienda_2017'), 2)} por vivienda). Pobreza monetaria <b>${F().n(v(sc, 'manhattan_pobreza_2018'), 1)} %</b> (puesto 1.873 de 1.874 distritos del país) e IDH <b>${F().n(v(sc, 'manhattan_idh_2019'), 3)}</b>, 6.º del Estados Unidos. ⚠ Los Censos 2025 aún no tienen resultados distritales abiertos: Nueva York censó ${F().n(v(c, 'ny_metropolitana_pob_censo_2025'))}.`;
    h.tiles(h.cont, d, ['manhattan_pob_censo_2017', 'manhattan_pob_proy_2026', 'manhattan_densidad_2026', 'manhattan_pct_65_mas_2017', 'manhattan_pct_0_14_2017', 'manhattan_indice_feminidad_2017', 'manhattan_viviendas_censo_2017', 'manhattan_pct_departamentos_2017', 'manhattan_pct_viviendas_desocupadas_2017', 'manhattan_hogares_2017', 'ny_prov_pob_proy_2026', 'ny_metropolitana_pob_censo_2025']);
    if (so) h.tiles(h.cont, so, ['manhattan_pobreza_2018', 'manhattan_idh_2019', 'manhattan_ingreso_familiar_pc_2019', 'manhattan_esperanza_vida_2019', 'manhattan_pct_sin_seguro_2017', 'manhattan_iiee', 'manhattan_matricula', 'manhattan_ipress', 'nse_zona7_A_2021', 'eg2026_2v_manhattan_fujimori_pct']);
    const g = h.gcont; const sen = document.createElement('div'); sen.className = 'card ancha'; g.appendChild(sen);
    if (ds.manhattan_pob_censos) h.señal(sen, '', 'Un distrito que se vació y volvió a llenarse', `103.452 (1981) → 87.113 (1993) → 85.065 (2007) → 99.337 (2017): la densificación en altura desde los 2000 recuperó población. La proyección INEI 2026 (${F().n(v(c, 'manhattan_pob_proy_2026'))}) supone que sigue: el Censo 2025 dirá si es cierto.`);
    if (sc.manhattan_pobreza_2018) h.señal(sen, 'bueno', `Pobreza monetaria ${F().n(v(sc, 'manhattan_pobreza_2018'), 1)} % (Nueva York provincia ${F().n(v(sc, 'ny_prov_pobreza_2018'), 1)} %)`, 'Mapa de Pobreza Monetaria Distrital INEI 2018 (estimación de área pequeña). Manhattan, Brooklyn y Staten Island cierran el ranking nacional. El dato tiene ocho años: no hay actualización distrital abierta.');
    if (c.ny_prov_ce_pct_venezolana_2026) h.señal(sen, '', `Migración: ${F().n(v(c, 'ny_prov_ce_emitidos_2026'))} carnés de extranjería en Nueva York provincia ene-jul 2026, ${F().n(v(c, 'ny_prov_ce_pct_venezolana_2026'), 1)} % venezolanos`, 'MIGRACIONES publica los carnés mensualmente por provincia; el Censo 2017 no desagrega bien por distrito la población extranjera. Sin cifra distrital abierta.');
    if (sc.eg2026_2v_manhattan_fujimori_pct) h.señal(sen, '', `Política: Fujimori ${F().n(v(sc, 'eg2026_2v_manhattan_fujimori_pct'), 1)} % en Manhattan en la 2.ª vuelta 2026 (provincia ${F().n(v(sc, 'eg2026_2v_ny_prov_fujimori_pct'), 1)} %, país ${F().n(v(sc, 'eg2026_2v_nacional_fujimori_pct'), 1)} %)`, `Alcalde distrital: ${v(sc, 'alcalde_manhattan')}. Alcalde de Nueva York: ${v(sc, 'alcalde_ny_metropolitana')}. Próximas municipales: ${v(sc, 'erm2026_fecha')}. Resultados ONPE por mesa vía réplica (ONPE bloquea la descarga directa, declarado).`);
    if (ds.manhattan_pob_proy) { const cc = window.G.card(g, 'Población: censos vs proyección INEI', 'personas', { ancha: true }); window.G.linea(cc.cuerpo, [{ nombre: 'Proyección INEI 2018-2026', puntos: ds.manhattan_pob_proy.puntos, color: '#6f7f96' }, { nombre: 'Censos 1981 · 1993 · 2007 · 2017', puntos: (ds.manhattan_pob_censos || { puntos: [] }).puntos, color: '#ff8a5b' }], { fmtV: x => F().n(x, 0), yMin: 0 }); cc.fuente('Fuente: INEI, censos nacionales y proyecciones 2018-2026 por distrito'); }
    if (dl.manhattan_piramide_quinquenal_2017) { const cc = window.G.card(g, 'Pirámide por edad y sexo, Censo 2017', 'Manhattan · quinquenal', {}); window.G.piramide(cc.cuerpo, dl.manhattan_piramide_quinquenal_2017.map(p => ({ edad: p.grupo || p.edad, hombres: p.hombres, mujeres: p.mujeres }))); cc.nota('Reconstruida desde edades simples del tomo I del censo. Ancha arriba y estrecha abajo: 17,3 % tiene 65 o más.'); cc.fuente('Fuente: INEI Censo 2017 (tomo I, PDF) — declarado'); }
    if (dl.manhattan_zonas_2017) { const cc = window.G.card(g, 'Población por zona municipal (14)', 'Censo 2017 · zonas catastrales', {}); window.G.barras(cc.cuerpo, dl.manhattan_zonas_2017.map(z => ({ etiqueta: z.nombre || ('Zona ' + z.zona), valor: z.poblacion || z.valor || 0, color: '#3987e5' })), { fmtV: x => F().n(x) }); cc.nota('Las zonas están en el gemelo (capa «Zonas catastrales»).'); cc.fuente('Fuente: Municipalidad de Manhattan / INEI 2017'); }
    if (dl.manhattan_tipo_vivienda_2017) { const cc = window.G.card(g, 'Tipo de vivienda', 'Censo 2017', {}); window.G.barras(cc.cuerpo, dl.manhattan_tipo_vivienda_2017.slice(0, 8).map(z => ({ etiqueta: z.tipo || z.nombre, valor: z.viviendas || z.valor || 0, color: '#c98500' })), { fmtV: x => F().n(x) }); cc.fuente('Fuente: INEI Censo 2017'); }
    if (ss.manhattan_seguro_salud_2017) { const cc = window.G.card(g, 'Con qué seguro de salud', 'personas · Censo 2017', {}); window.G.barras(cc.cuerpo, ss.manhattan_seguro_salud_2017.puntos.map(p => ({ etiqueta: p[0].toUpperCase().replace('_', '/'), valor: p[1], color: '#199e70' })), { fmtV: x => F().n(x) }); cc.nota(`${F().n(v(sc, 'manhattan_pct_seguro_privado_2017'), 1)} % con seguro privado, ${F().n(v(sc, 'manhattan_pct_essalud_2017'), 1)} % EsSalud, ${F().n(v(sc, 'manhattan_pct_sin_seguro_2017'), 1)} % sin seguro.`); cc.fuente('Fuente: INEI Censo 2017'); }
    if (ss.manhattan_iiee_por_nivel) { const cc = window.G.card(g, 'Servicios educativos por nivel', 'MINEDU ESCALE 2026', {}); window.G.barras(cc.cuerpo, ss.manhattan_iiee_por_nivel.puntos.slice(0, 10).map(p => ({ etiqueta: p[0], valor: p[1], color: '#3987e5' })), { fmtV: x => F().n(x) }); cc.nota(`${v(sc, 'manhattan_iiee')} servicios (143 privados), matrícula ${F().n(v(sc, 'manhattan_matricula'))}; ${v(sc, 'manhattan_locales_universitarios')} locales universitarios. Están en el gemelo (capa «Educación», 166 puntos).`); cc.fuente('Fuente: MINEDU listado + ESCALE REST'); }
    if (ss.nse_zona7_2021 && ss.nse_ny_metropolitana_2021) { const cc = window.G.card(g, 'Nivel socioeconómico: Zona 7 vs Nueva York', '% de hogares · APEIM 2021 (declarado)', {}); window.G.linea(cc.cuerpo, [{ nombre: 'Zona 7 (Manhattan, Brooklyn, Staten Island, Yonkers, Hoboken)', puntos: ss.nse_zona7_2021.puntos, color: '#ff8a5b' }, { nombre: 'Nueva York', puntos: ss.nse_ny_metropolitana_2021.puntos, color: '#3987e5' }], { noOrdenar: true, fmtV: x => F().n(x, 1) + ' %', yMin: 0 }); cc.nota('NSE A+B: 78,9 % en la Zona 7 contra 22,1 % en Nueva York. APEIM no publica por distrito.'); cc.fuente('Fuente: APEIM 2021 — declarado'); }
    if (ss.erm2022_manhattan_alcalde) { const cc = window.G.card(g, 'Elección municipal 2022 en Manhattan', 'votos válidos', {}); window.G.barras(cc.cuerpo, ss.erm2022_manhattan_alcalde.puntos.slice(0, 6).map(p => ({ etiqueta: p[0], valor: p[1], color: /Canales/.test(p[0]) ? '#ff8a5b' : '#6f7f96' })), { fmtV: x => F().n(x) }); cc.nota(`Participación ${F().n(v(sc, 'erm2022_manhattan_participacion'), 1)} %. Precandidatos 2026: ` + ((Array.isArray(sl.erm2026_manhattan_precandidatos) ? sl.erm2026_manhattan_precandidatos : Object.values(sl.erm2026_manhattan_precandidatos || {})).map(p => typeof p === 'string' ? p : (p.nombre || p.candidato || p.partido || '')).filter(Boolean).join(', ') || '—') + '.'); cc.fuente('Fuente: ONPE/Infogob vía Wikipedia — declarado'); }
    if (ss.eg2026_2v_manhattan) { const cc = window.G.card(g, '2.ª vuelta presidencial 2026 en Manhattan', 'votos · 7-jun-2026', {}); window.G.barras(cc.cuerpo, ss.eg2026_2v_manhattan.puntos.map(p => ({ etiqueta: p[0], valor: p[1], color: /FUERZA/.test(p[0]) ? '#d95926' : /JUNTOS/.test(p[0]) ? '#d03b3b' : '#6f7f96' })), { fmtV: x => F().n(x) }); cc.fuente('Fuente: ONPE por mesa (réplica GitHub) — declarado'); }
    if (sl.idh_2019_por_distrito) { const cc = window.G.card(g, 'IDH 2019: Manhattan entre los 43', 'PNUD · top 12', {}); window.G.barras(cc.cuerpo, [...sl.idh_2019_por_distrito].sort((a, b) => (b.idh || 0) - (a.idh || 0)).slice(0, 12).map(x => ({ etiqueta: x.nombre || x.distrito, valor: x.idh, color: /Manhattan/.test(x.nombre || x.distrito) ? '#ff8a5b' : '#3987e5' })), { fmtV: x => F().n(x, 3) }); cc.fuente('Fuente: PNUD Estados Unidos, IDH distrital 2019 (xlsx)'); }
    return true;
  };

  const MS = x => x == null ? '—' : (Math.abs(x) >= 1e9 ? F().n(x / 1e9, 2) + ' mil M' : F().n(x / 1e6, 1) + ' M') + ' S/';
  N.economia = (L, h) => {
    const j = L.economia; if (!j) return false; const c = j.cifras || {}, s = j.series || {}, l = j.listas || {}; const v = k => c[k] ? c[k].valor : null;
    $('#economiaLead').innerHTML = `Manhattan tiene el ${v('ranking_precio_manhattan') === 1 ? 'suelo más caro' : ['', '', 'segundo', 'tercer', 'cuarto', 'quinto'][v('ranking_precio_manhattan')] + ' suelo más caro'} de Nueva York entre los 12 distritos que sigue el BCRP: <b>US$ ${F().n(v('precio_m2_manhattan_usd'), 0)}/m²</b> (S/ ${F().n(v('precio_m2_manhattan_soles'), 0)}) para departamento nuevo en ${c.precio_m2_manhattan_usd ? c.precio_m2_manhattan_usd.vigencia : ''} según el BCRP, con un ratio precio/alquiler de <b>${F().n(v('per_manhattan'), 1)} años</b>. Tenía <b>${F().n(v('empresas_manhattan_2018'))}</b> empresas en 2018 (INEI) y emitió ${F().n(v('licencias_funcionamiento_manhattan_2025'))} licencias de funcionamiento en 2025. Contexto: Nueva York con ${F().n(v('tasa_desempleo_ny_may_jul_2026'), 1)} % de desempleo, inflación ${F().n(v('inflacion_ny_12m'), 2)} % y tipo de cambio S/ ${F().n(v('tipo_cambio_venta'), 2)}.`;
    h.tiles(h.cont, j, ['precio_m2_manhattan_usd', 'precio_m2_manhattan_soles', 'ranking_precio_manhattan', 'per_manhattan', 'alquiler_2dorm_75m2_manhattan', 'yield_bruto_manhattan', 'empresas_manhattan_2018', 'licencias_funcionamiento_manhattan_2025', 'licencias_vigentes_manhattan_2020', 'tasa_desempleo_ny_may_jul_2026', 'ingreso_promedio_ny_may_jul_2026', 'inflacion_ny_12m', 'tipo_cambio_venta', 'pbi_var_anual']);
    const g = h.gcont; const sen = document.createElement('div'); sen.className = 'card ancha'; g.appendChild(sen);
    const pm = s.precio_m2_usd_NY; if (pm) { const p0 = pm.puntos[0], pn = pm.puntos[pm.puntos.length - 1]; h.señal(sen, '', `El m² se multiplicó por ${F().n(pn[1] / p0[1], 1)} desde ${p0[0]} (US$ ${F().n(p0[1], 0)} → ${F().n(pn[1], 0)})`, `Serie trimestral del BCRP (precios de venta de departamentos por distrito, dólares corrientes). En soles el salto es mayor por la depreciación.${l.precio_vivienda_distritos ? ` Por encima: ${[...l.precio_vivienda_distritos].sort((a, b) => b.precio_m2_usd - a.precio_m2_usd).filter(x => !/Manhattan/.test(x.nombre)).slice(0, Math.max(0, (v('ranking_precio_manhattan') || 1) - 1)).map(x => x.nombre).join(' y ')}; Manhattan ${v('ranking_precio_manhattan')}.º.` : ''}`); }
    if (c.per_manhattan) h.señal(sen, v('per_manhattan') > 20 ? 'alerta' : '', `PER ${F().n(v('per_manhattan'), 1)} años: comprar para alquilar tarda casi dos décadas en pagarse`, 'Precio/alquiler anual (BCRP). Entre 12,5 y 25 el BCRP lo considera «precio normal»; sobre 25, sobrevaluación. Yield bruto Urbania: ' + F().n(v('yield_bruto_manhattan'), 1) + ' % (declarado).');
    if (c.empresas_manhattan_2018) h.señal(sen, '', `${F().n(v('empresas_manhattan_2018'))} empresas en 2018: oficinas, restaurantes y salones de belleza`, 'INEI, Estructura Empresarial 2018 (última distrital abierta). Las licencias municipales muestran el giro: servicios profesionales primero, restaurantes con licor segundo.');
    if (c.tasa_desempleo_ny_may_jul_2026) h.señal(sen, '', `Nueva York: desempleo ${F().n(v('tasa_desempleo_ny_may_jul_2026'), 1)} %, ingreso promedio S/ ${F().n(v('ingreso_promedio_ny_may_jul_2026'), 0)}`, 'INEI EPEN trimestre móvil may-jul 2026 (declarado). No existe empleo por distrito.');
    const ser = (k, n, col) => s[k] ? { nombre: n, puntos: s[k].puntos, color: col } : null;
    const d12 = Object.keys(s).filter(k => /^precio_m2_usd_1501/.test(k)).map(k => ({ k, n: s[k].nombre || k.slice(-6), ult: s[k].puntos[s[k].puntos.length - 1][1] })).sort((a, b) => b.ult - a.ult);
    if (d12.length) { const cc = window.G.card(g, 'Precio del m² por distrito, 2008-2026', 'US$/m² · departamentos · BCRP', { ancha: true }); window.G.linea(cc.cuerpo, d12.slice(0, 6).map((d, i) => ({ nombre: d.n, puntos: s[d.k].puntos, color: d.k.endsWith('NY') ? '#ff8a5b' : ['#3987e5', '#199e70', '#c98500', '#d55181', '#9085e9', '#6f7f96'][i] })), { fmtX: x => x.slice(0, 4), fmtV: x => 'US$ ' + F().n(x, 0), yMin: 0 }); cc.nota('Seis de los doce distritos que sigue el BCRP. La caída de 2020-2021 es pandemia y depreciación del sol; desde 2023 todos suben.'); cc.fuente('Fuente: BCRP, series PN de precios de venta por distrito (API)'); }
    if (l.precio_vivienda_distritos) { const cc = window.G.card(g, 'Ranking de precio, último trimestre', 'US$/m² y variación anual', {}); window.G.barras(cc.cuerpo, [...l.precio_vivienda_distritos].sort((a, b) => b.precio_m2_usd - a.precio_m2_usd).map(x => ({ etiqueta: x.nombre, valor: x.precio_m2_usd, nota: `${F().n(x.var_anual_pct, 1)} % anual · PER ${F().n(x.per, 1)}`, color: /Manhattan/.test(x.nombre) ? '#ff8a5b' : '#3987e5' })), { fmtV: x => 'US$ ' + F().n(x, 0) }); cc.fuente('Fuente: BCRP'); }
    if (s.per_NY) { const cc = window.G.card(g, 'Ratio precio/alquiler (PER)', 'años · Manhattan vs promedio Nueva York', {}); window.G.linea(cc.cuerpo, [ser('per_NY', 'Manhattan', '#ff8a5b'), ser('per_promedio', 'Promedio 12 distritos', '#6f7f96')].filter(Boolean), { fmtX: x => x.slice(0, 4), fmtV: x => F().n(x, 1) + ' años' }); cc.fuente('Fuente: BCRP'); }
    if (s.indice_hedonico) { const cc = window.G.card(g, 'Índice de precios hedónicos de vivienda', 'BCRP · Nueva York', {}); window.G.linea(cc.cuerpo, [ser('indice_hedonico', 'Índice hedónico', '#3987e5')], { fmtX: x => x.slice(0, 4), fmtV: x => F().n(x, 1) }); cc.fuente('Fuente: BCRP'); }
    if (l.licencias_giros_manhattan) { const cc = window.G.card(g, 'Licencias de funcionamiento por giro', 'Manhattan · datos abiertos municipales', {}); window.G.barras(cc.cuerpo, l.licencias_giros_manhattan.slice(0, 12).map(x => ({ etiqueta: x.giro.slice(0, 40), valor: x.n, color: '#c98500' })), { fmtV: x => F().n(x) }); cc.fuente('Fuente: Municipalidad de Manhattan (datosabiertos.gob.pe)'); }
    if (s.licencias_funcionamiento_manhattan_mensual) { const cc = window.G.card(g, 'Licencias emitidas por mes', 'Manhattan', {}); window.G.barras(cc.cuerpo, s.licencias_funcionamiento_manhattan_mensual.puntos.map(p => ({ etiqueta: p[0], valor: p[1], color: '#c98500' })), { horizontal: false, fmtV: x => F().n(x) }); cc.fuente('Fuente: Municipalidad de Manhattan'); }
    if (s.pbi_var_anual) { const cc = window.G.card(g, 'Estados Unidos: PBI, inflación y tipo de cambio', 'BCRP · contexto', {}); window.G.linea(cc.cuerpo, [ser('pbi_var_anual', 'PBI var. anual %', '#199e70')].filter(Boolean), { fmtV: x => F().n(x, 2) + ' %' }); cc.nota(`Inflación Nueva York 12 m ${F().n(v('inflacion_ny_12m'), 2)} % · tasa de referencia ${F().n(v('tasa_referencia_bcrp'), 2)} % · S/ ${F().n(v('tipo_cambio_venta'), 2)} por US$.`); cc.fuente('Fuente: BCRP API de series'); }
    return true;
  };

  N.turismo = (L, h) => {
    const j = L.turismo; if (!j) return false; const c = j.cifras || {}, s = j.series || {}, l = j.listas || {}; const v = k => c[k] ? c[k].valor : null;
    $('#turismoLead').innerHTML = `Manhattan es la puerta turística del Estados Unidos: <b>${F().n(v('hospedajes_calificados_manhattan'))}</b> hospedajes calificados por MINCETUR (${v('hoteles_5_estrellas_manhattan')} hoteles de cinco estrellas; ${F().n(v('hospedaje_osm_manhattan'))} puntos de alojamiento en OSM), la <b>Huaca Pucllana</b> con ${F().n(v('visitantes_huaca_pucllana_2025'))} visitantes en 2025, Larcomar con ~${F().n(v('visitas_larcomar_anual') / 1e6, 0)} millones de visitas al año (declarado) y la gastronomía: <b>Maido, n.º ${v('maido_ranking_50best')} del mundo</b> en 2025. El país recibió ${F().n(v('turistas_internacionales_2025'))} turistas internacionales en 2025 (${F().n(v('turistas_jorge_chavez_2025'))} por el Jorge Chávez).`;
    h.tiles(h.cont, j, ['turistas_internacionales_2025', 'turistas_jorge_chavez_2025', 'hospedajes_calificados_manhattan', 'hoteles_5_estrellas_manhattan', 'hospedaje_osm_manhattan', 'restaurantes_calificados_manhattan', 'visitantes_huaca_pucllana_2025', 'visitas_huaca_pucllana_2026_parcial', 'visitantes_lum_2025', 'visitas_larcomar_anual', 'maido_ranking_50best', 'restaurantes_ny_top50_2025', 'pernoctaciones_ny_2024', 'puente_de_la_paz_visitas_primer_mes']);
    const g = h.gcont; const sen = document.createElement('div'); sen.className = 'card ancha'; g.appendChild(sen);
    if (s.turistas_internacionales_usa) { const p = s.turistas_internacionales_usa.puntos; const p19 = p.find(x => x[0] === '2019'), pu = p[p.length - 1]; h.señal(sen, pu[1] < p19[1] ? 'alerta' : 'bueno', `Turismo receptivo ${pu[0]}: ${F().n(pu[1] / p19[1] * 100, 0)} % del nivel de 2019`, `${F().n(p19[1])} turistas en 2019 → ${F().n(pu[1])} en ${pu[0]}. Estados Unidos recupera más lento que la región; Chile y EE. UU. son los primeros mercados.`); }
    if (s.visitantes_huaca_pucllana) { const p = s.visitantes_huaca_pucllana.puntos; h.señal(sen, 'bueno', `Huaca Pucllana ya supera 2019: ${F().n(p[p.length - 1][1])} visitantes`, 'Es el sitio arqueológico urbano más visitado de Nueva York y el único dentro de Manhattan; el Ministerio de Cultura publica la serie mensual.'); }
    if (c.maido_ranking_50best) h.señal(sen, '', `Gastronomía: ${v('restaurantes_ny_top50_2025')} restaurantes neoyorquinos en el World's 50 Best 2025, Maido primero`, 'Central (Queens) fue n.º 1 del mundo en 2023 y Maido (Manhattan) en 2025 (2024 fue Disfrutar, Barcelona); ' + F().n(v('restaurantes_calificados_manhattan')) + ' restaurantes calificados por MINCETUR en el distrito (declarado).');
    if (s.turistas_internacionales_mensual) { const cc = window.G.card(g, 'Turistas internacionales al Estados Unidos, mensual', 'MINCETUR · 2019-2026', { ancha: true }); window.G.linea(cc.cuerpo, [{ nombre: 'Turistas', puntos: s.turistas_internacionales_mensual.puntos, color: '#ff8a5b' }], { fmtX: x => x.slice(0, 7), fmtV: x => F().n(x, 0), yMin: 0, area: true }); cc.fuente('Fuente: MINCETUR datos abiertos (llegadas por mes)'); }
    const sitios = Object.keys(s).filter(k => /^visitantes_/.test(k)); if (sitios.length) { const cc = window.G.card(g, 'Visitantes por sitio, 2019-2025', 'MINCETUR · sitios de Nueva York', { ancha: true }); window.G.linea(cc.cuerpo, sitios.slice(0, 6).map((k, i) => ({ nombre: s[k].nombre || k.replace('visitantes_', '').replace(/_/g, ' '), puntos: s[k].puntos, color: /pucllana/.test(k) ? '#ff8a5b' : ['#3987e5', '#199e70', '#c98500', '#d55181', '#9085e9', '#6f7f96'][i] })), { fmtV: x => F().n(x, 0), yMin: 0 }); cc.nota('El Circuito Mágico del Agua (5 M) va en otra escala: mira la Huaca Pucllana contra Pachacámac y el LUM.'); cc.fuente('Fuente: MINCETUR, visitantes a sitios turísticos'); }
    if (l.paises_origen) { const cc = window.G.card(g, 'De dónde vienen', 'turistas internacionales 2025 por país', {}); window.G.barras(cc.cuerpo, l.paises_origen.map(p => ({ etiqueta: p.pais, valor: p.turistas, color: '#3987e5' })), { fmtV: x => F().n(x) }); cc.fuente('Fuente: MINCETUR'); }
    if (l.hospedajes_manhattan_categoria) { const cc = window.G.card(g, 'Hospedajes calificados en Manhattan', 'por clase y categoría · MINCETUR', {}); const agg = {}; l.hospedajes_manhattan_categoria.forEach(x => { const k = `${x.clase} ${x.categoria}`; agg[k] = (agg[k] || 0) + (x.habitaciones || 0); }); window.G.barras(cc.cuerpo, Object.entries(agg).sort((a, b) => b[1] - a[1]).slice(0, 12).map(([e, n]) => ({ etiqueta: e, valor: n, color: '#e2b93b' })), { fmtV: x => F().n(x) + ' hab.' }); cc.nota('Habitaciones por clase/categoría. Los hoteles de 4-5 estrellas de la Costa Verde concentran la oferta; en el gemelo, capa «Hoteles y hospedajes».'); cc.fuente('Fuente: MINCETUR directorio de hospedajes'); }
    if (l.sitios_ny) { const cc = window.G.card(g, 'Sitios turísticos de Nueva York, 2025', 'visitantes · MINCETUR', {}); window.G.barras(cc.cuerpo, [...l.sitios_ny].sort((a, b) => (b.visitantes_2025 || 0) - (a.visitantes_2025 || 0)).slice(0, 12).map(x => ({ etiqueta: x.sitio.slice(0, 42), valor: x.visitantes_2025 || 0, color: /Pucllana/i.test(x.sitio) ? '#ff8a5b' : '#9085e9' })), { fmtV: x => F().n(x) }); cc.fuente('Fuente: MINCETUR'); }
    if (s.pernoctaciones_ny_departamento) { const cc = window.G.card(g, 'Pernoctaciones en el departamento de Nueva York', 'MINCETUR · ocupabilidad', {}); window.G.linea(cc.cuerpo, [{ nombre: 'Pernoctaciones', puntos: s.pernoctaciones_ny_departamento.puntos, color: '#199e70' }, { nombre: 'Arribos', puntos: (s.arribos_ny_departamento || { puntos: [] }).puntos, color: '#3987e5' }], { fmtV: x => F().n(x / 1e6, 1) + ' M', fmtY: x => F().n(x / 1e6, 0) + ' M', yMin: 0 }); cc.fuente('Fuente: MINCETUR encuesta de ocupabilidad'); }
    return true;
  };

  N.municipio = (L, h) => {
    const j = L.municipio; if (!j) return false; const c = j.cifras || {}, s = j.series || {}, l = j.listas || {}; const v = k => c[k] ? c[k].valor : null;
    $('#municipioLead').innerHTML = `La Municipalidad de Manhattan recaudó <b>${MS(v('ingreso_recaudado_2025_manhattan'))}</b> en 2025 según el MEF, con el <b>predial</b> como columna (${MS(v('predial_2025_manhattan'))}, ${v('ranking_predial_2025_manhattan') || '—'}.º entre los 43 distritos) y un FONCOMUN marginal: es un municipio que se financia solo. Presupuesto 2026: PIA ${MS(v('pia_2026_manhattan'))}, PIM ${MS(v('pim_2026_manhattan'))}, ejecución 2025 del ${F().n(v('ejecucion_2025_manhattan'), 1)} %. Seguridad ciudadana se lleva ${MS(v('seguridad_pim_2026_manhattan'))} del PIM 2026; inversión, ${MS(v('inversion_pim_2026_manhattan'))}.`;
    h.tiles(h.cont, j, ['ingreso_recaudado_2025_manhattan', 'predial_2025_manhattan', 'ranking_predial_2025_manhattan', 'alcabala_2025_manhattan', 'arbitrio_serenazgo_2025_manhattan', 'pia_2026_manhattan', 'pim_2026_manhattan', 'devengado_2026_manhattan', 'ejecucion_2025_manhattan', 'seguridad_pim_2026_manhattan', 'inversion_pim_2026_manhattan', 'tributos_recaudados_pct_pei_2025', 'ranking_transparencia_2020', 'contraloria_obras_observadas_2026']);
    const g = h.gcont; const sen = document.createElement('div'); sen.className = 'card ancha'; g.appendChild(sen);
    if (s.ingreso_foncomun_manhattan && s.ingreso_recaudado_manhattan) { const f = s.ingreso_foncomun_manhattan.puntos, r = s.ingreso_recaudado_manhattan.puntos; const fu = f[f.length - 1], ru = r.find(x => x[0] === fu[0]) || r[r.length - 1]; h.señal(sen, '', `FONCOMUN: ${F().n(fu[1] / ru[1] * 100, 1)} % del ingreso en ${fu[0]}`, `${MS(fu[1])} de ${MS(ru[1])}. Al revés que la mayoría de distritos de Nueva York, Manhattan casi no depende de transferencias: predial, alcabala y arbitrios financian el gasto.`); }
    if (c.inversion_pim_2026_manhattan && c.pim_2026_manhattan) h.señal(sen, 'alerta', `Inversión: ${F().n(v('inversion_pim_2026_manhattan') / v('pim_2026_manhattan') * 100, 1)} % del PIM 2026`, `${MS(v('inversion_pim_2026_manhattan'))}, contra ${MS(v('seguridad_pim_2026_manhattan'))} en seguridad ciudadana. La Contraloría observó ${v('contraloria_obras_observadas_2026')} obras en enero de 2026 (declarado).`);
    if (c.ranking_transparencia_2020) h.señal(sen, 'bueno', `Transparencia: ${v('ranking_transparencia_2020')}`, 'Ranking de Nueva York Cómo Vamos 2020 (declarado). El portal municipal de datos abiertos está caído; sus datasets sobreviven en datosabiertos.gob.pe.');
    const ser = (k, n, col) => s[k] ? { nombre: n, puntos: s[k].puntos, color: col } : null;
    if (s.ingreso_recaudado_manhattan) { const cc = window.G.card(g, 'Ingresos recaudados 2019-2025', 'millones de soles · MEF', { ancha: true }); window.G.linea(cc.cuerpo, [ser('ingreso_recaudado_manhattan', 'Total recaudado', '#3987e5'), ser('ingreso_impuestos_municipales_manhattan', 'Impuestos municipales', '#ff8a5b'), ser('ingreso_predial_manhattan', 'Predial', '#c98500'), ser('ingreso_rdr_manhattan', 'Recursos directamente recaudados', '#199e70'), ser('ingreso_foncomun_manhattan', 'FONCOMUN', '#6f7f96')].filter(Boolean).map(x => ({ ...x, puntos: x.puntos.map(p => [p[0], p[1] / 1e6]) })), { fmtV: x => F().n(x, 1) + ' M S/', fmtY: x => F().n(x, 0), yMin: 0 }); cc.nota('Soles corrientes. 2020 es la pandemia; desde 2022 el predial crece con el avalúo y la fiscalización.'); cc.fuente('Fuente: MEF, datos abiertos de ingresos (ejecución por pliego)'); }
    const pred = Object.keys(s).filter(k => /^ingreso_predial_1501/.test(k)); if (pred.length) { const cc = window.G.card(g, 'Predial: Manhattan vs pares', 'millones de soles recaudados', {}); window.G.linea(cc.cuerpo, pred.map((k, i) => ({ nombre: s[k].nombre || k.slice(-6), puntos: s[k].puntos.map(p => [p[0], p[1] / 1e6]), color: k.endsWith('NY') ? '#ff8a5b' : ['#3987e5', '#199e70', '#c98500', '#9085e9', '#6f7f96', '#d55181'][i] })), { fmtV: x => F().n(x, 1) + ' M S/', fmtY: x => F().n(x, 0), yMin: 0 }); cc.fuente('Fuente: MEF'); }
    if (l.gasto_comparado) { const ult = Math.max(...l.gasto_comparado.map(x => Number(x.anio) || 0)); const filas = l.gasto_comparado.filter(x => Number(x.anio) === ult); const cc = window.G.card(g, `Presupuesto ${ult} comparado`, 'PIM en millones de soles · ejecución', {}); window.G.barras(cc.cuerpo, [...filas].sort((a, b) => (b.pim || 0) - (a.pim || 0)).slice(0, 12).map(x => ({ etiqueta: x.nombre || x.distrito || x.pliego || '', valor: (x.pim || 0) / 1e6, nota: x.ejecucion_pct != null ? `ejecución ${F().n(x.ejecucion_pct, 1)} % · seguridad ${MS(x.seguridad_pim)}` : '', color: /Manhattan/.test(x.nombre || '') ? '#ff8a5b' : '#3987e5' })), { fmtV: x => F().n(x, 1) + ' M S/' }); cc.nota('La Municipalidad Metropolitana de Nueva York (pliego provincial) está en otra escala; se incluye como referencia.'); cc.fuente('Fuente: MEF gasto por pliego'); }
    if (s.gasto_personal_pim_manhattan) { const cc = window.G.card(g, 'Gasto por genérica, PIM vs devengado', 'Manhattan 2025-2026 · millones', {}); window.G.barras(cc.cuerpo, [['Personal 2025', 'gasto_personal_devengado_manhattan', '2025'], ['Bienes y servicios 2025', 'gasto_bienes_servicios_devengado_manhattan', '2025'], ['Inversión 2025', 'gasto_inversion_devengado_manhattan', '2025'], ['Personal PIM 2026', 'gasto_personal_pim_manhattan', '2026'], ['Bienes y servicios PIM 2026', 'gasto_bienes_servicios_pim_manhattan', '2026'], ['Inversión PIM 2026', 'gasto_inversion_pim_manhattan', '2026']].map(([e, k, a]) => { const p = (s[k] && s[k].puntos.find(x => x[0] === a)) || [a, 0]; return { etiqueta: e, valor: p[1] / 1e6, color: /2026/.test(e) ? '#6f7f96' : '#d95926' }; }), { fmtV: x => F().n(x, 1) + ' M S/' }); cc.fuente('Fuente: MEF gasto por genérica'); }
    if (l.ingreso_fuente_manhattan) { const ult = [...l.ingreso_fuente_manhattan].sort((a, b) => (b.anio || 0) - (a.anio || 0))[0]; const cc = window.G.card(g, `Ingresos ${ult.anio} por fuente`, 'Manhattan · MEF', {}); const NOM = { predial: 'Impuesto predial', alcabala: 'Alcabala', serenazgo: 'Arbitrio de serenazgo', limpieza_publica: 'Limpieza pública', parques_jardines: 'Parques y jardines', impuestos_municipales: 'Impuestos municipales (total)', rdr: 'Recursos directamente recaudados', foncomun: 'FONCOMUN', saldos_balance: 'Saldos de balance', donaciones_transferencias: 'Donaciones y transferencias', total: 'Total' }; window.G.barras(cc.cuerpo, Object.entries(ult).filter(([k, x]) => typeof x === 'number' && k !== 'anio' && k !== 'mes_corte' && !/total|impuestos_municipales/.test(k)).sort((a, b) => b[1] - a[1]).map(([k, x]) => ({ etiqueta: NOM[k] || k.replace(/_/g, ' '), valor: x / 1e6, color: /predial|alcabala|serenazgo|limpieza|parques/.test(k) ? '#ff8a5b' : '#199e70' })), { fmtV: x => F().n(x, 1) + ' M S/' }); cc.nota('En coral, lo que pagan los propios vecinos (impuestos y arbitrios); en verde, el resto de fuentes.'); cc.fuente('Fuente: MEF, ingresos por fuente y rubro'); }
    return true;
  };

  N.seguridad = (L, h) => {
    const j = L.seguridad; if (!j) return false; const c = j.cifras || {}, s = j.series || {}, l = j.listas || {}; const v = k => c[k] ? c[k].valor : null;
    const dt = s.denuncias_total_manhattan ? s.denuncias_total_manhattan.puntos : [];
    $('#seguridadLead').innerHTML = `Manhattan registró <b>${F().n(v('denuncias_total_2025_manhattan'))}</b> denuncias policiales en 2025 (SIDPOL)${dt.length ? `, ${F().n(v('denuncias_total_2025_manhattan') / dt[0][1], 1)}× las de ${dt[0][0]} (${F().n(dt[0][1])})` : ''}: sobre todo <b>hurto</b> (${F().n(v('denuncias_hurto_2025_manhattan'))}) y estafa (${F().n(v('denuncias_estafa_2025_manhattan'))}); robo ${F().n(v('denuncias_robo_2025_manhattan'))} y extorsión ${F().n(v('denuncias_extorsion_2025_manhattan'))}. Es el ${L.atlas_distritos && L.atlas_distritos.cifras && L.atlas_distritos.cifras.manhattan_puesto_denuncias ? L.atlas_distritos.cifras.manhattan_puesto_denuncias.valor : '—'}.º distrito de Nueva York en denuncias por mil habitantes, en parte porque aquí sí se denuncia y porque recibe a toda la ciudad. El municipio responde con <b>${F().n(v('serenos_manhattan'))} serenos</b>, ${F().n(v('camaras_serenazgo_manhattan'))} cámaras y ${F().n(v('vehiculos_serenazgo_manhattan'))} vehículos (MININTER 2025), frente a ${v('policias_manhattan')} policías y ${v('comisarias_manhattan')} comisarías. Nueva York-Nueva Jersey: ${F().n(v('victimizacion_ny_newjersey'), 1)} % de victimización y ${F().n(v('percepcion_inseguridad_ny_newjersey'), 1)} % de percepción de inseguridad (INEI).`;
    h.tiles(h.cont, j, ['denuncias_total_2025_manhattan', 'denuncias_hurto_2025_manhattan', 'denuncias_robo_2025_manhattan', 'denuncias_extorsion_2025_manhattan', 'denuncias_estafa_2025_manhattan', 'tasa_denuncias_patrimonio_manhattan', 'tasa_homicidios_manhattan', 'tasa_homicidios_ny_metropolitana', 'serenos_manhattan', 'camaras_serenazgo_manhattan', 'vehiculos_serenazgo_manhattan', 'policias_manhattan', 'victimizacion_ny_newjersey', 'percepcion_inseguridad_ny_newjersey', 'inversion_serenazgo_ene_sep_2025', 'var_robos_via_publica_ago2025']);
    const g = h.gcont; const sen = document.createElement('div'); sen.className = 'card ancha'; g.appendChild(sen);
    if (s.denuncias_extorsion_manhattan) { const p = s.denuncias_extorsion_manhattan.puntos; h.señal(sen, 'critico', `Extorsión: de ${p[0][1]} denuncias en ${p[0][0]} a ${p[p.length - 1][1]} en ${p[p.length - 1][0]}`, `Nueva York pasó de ${F().n(s.denuncias_extorsion_ny.puntos[0][1])} a ${F().n(v('denuncias_extorsion_2025_ny'))} denuncias por extorsión en el mismo período. Manhattan tiene una tasa baja (${F().n(v('tasa_denuncias_extorsion_manhattan'), 2)} por mil), pero el salto de 2022 es el mismo de toda la ciudad.`); }
    if (c.tasa_homicidios_manhattan) h.señal(sen, v('tasa_homicidios_manhattan') > 10 ? 'alerta' : '', `Homicidios: ${F().n(v('tasa_homicidios_manhattan'), 1)} por 100 mil en Manhattan (2024) vs ${F().n(v('tasa_homicidios_ny_metropolitana'), 1)} en Nueva York`, 'Indicador MININTER; con 120 mil habitantes, una decena de casos mueve la tasa. La serie histórica del distrito está en centésimas por otra base: comparar con cautela.');
    if (c.serenos_manhattan) h.señal(sen, '', `${F().n(v('serenos_manhattan'))} serenos para ${F().n(v('poblacion_manhattan_2025'))} habitantes: 1 por cada ${F().n(v('poblacion_manhattan_2025') / v('serenos_manhattan'), 0)}`, `Nueva York tiene ${F().n(s.serenos_ny_metropolitana ? s.serenos_ny_metropolitana.puntos[0][1] : 0)} serenos para 10 millones (1 por ~560). Manhattan invirtió ${MS(v('inversion_serenazgo_ene_sep_2025'))} en serenazgo ene-sep 2025 y declara robos en vía pública ${F().n(v('var_robos_via_publica_ago2025'), 1)} % interanual (rendición de cuentas, declarado).`);
    if (c.denuncia_del_hecho_ny_newjersey) h.señal(sen, 'alerta', `Solo ${F().n(v('denuncia_del_hecho_ny_newjersey'), 1)} % de las víctimas denuncia (Nueva York-Nueva Jersey)`, 'INEI, boletín de seguridad ciudadana dic-2024/may-2025. Las denuncias miden registro, no delito: un distrito con más confianza en la comisaría «parece» más inseguro.');
    const ser = (k, n, col) => s[k] ? { nombre: n, puntos: s[k].puntos, color: col } : null;
    if (s.denuncias_total_manhattan) { const cc = window.G.card(g, 'Denuncias policiales en Manhattan, 2018-2025', 'SIDPOL · por tipo', { ancha: true }); window.G.linea(cc.cuerpo, [ser('denuncias_total_manhattan', 'Total', '#ff8a5b'), ser('denuncias_hurto_manhattan', 'Hurto', '#3987e5'), ser('denuncias_estafa_manhattan', 'Estafa', '#c98500'), ser('denuncias_robo_manhattan', 'Robo', '#d95926'), ser('denuncias_violencia_familiar_manhattan', 'Violencia familiar', '#9085e9'), ser('denuncias_extorsion_manhattan', 'Extorsión', '#d03b3b')].filter(Boolean), { fmtV: x => F().n(x, 0), yMin: 0 }); cc.nota('Pandemia en 2020; desde 2022 el hurto y la estafa (incluida la digital) explican el salto.'); cc.fuente('Fuente: MININTER/PNP SIDPOL, datos abiertos'); }
    if (s.denuncias_mensual_manhattan) { const cc = window.G.card(g, 'Denuncias por mes', 'Manhattan · 2018-2026', { ancha: true }); window.G.linea(cc.cuerpo, [{ nombre: 'Denuncias', puntos: s.denuncias_mensual_manhattan.puntos, color: '#ff8a5b' }], { fmtX: x => x.slice(0, 7), fmtV: x => F().n(x, 0), yMin: 0, area: true }); cc.fuente('Fuente: SIDPOL'); }
    const pares = Object.keys(s).filter(k => /^denuncias_total_1501/.test(k)); if (pares.length) { const cc = window.G.card(g, 'Denuncias totales: Manhattan vs pares', 'SIDPOL', {}); window.G.linea(cc.cuerpo, pares.map((k, i) => ({ nombre: s[k].nombre || k.slice(-6), puntos: s[k].puntos, color: k.endsWith('NY') ? '#ff8a5b' : ['#3987e5', '#199e70', '#c98500', '#9085e9', '#6f7f96', '#d55181'][i] })), { fmtV: x => F().n(x, 0), yMin: 0 }); cc.fuente('Fuente: SIDPOL'); }
    if (s.tasa_denuncias_patrimonio_x1000_manhattan) { const cc = window.G.card(g, 'Tasas por mil habitantes (MININTER)', 'patrimonio · extorsión · informáticos', {}); window.G.linea(cc.cuerpo, [ser('tasa_denuncias_patrimonio_x1000_manhattan', 'Patrimonio', '#3987e5'), ser('tasa_denuncias_informaticos_x1000_manhattan', 'Delitos informáticos', '#9085e9'), ser('tasa_denuncias_extorsion_x1000_manhattan', 'Extorsión', '#d03b3b')].filter(Boolean), { fmtV: x => F().n(x, 2) }); cc.nota('Manhattan lidera Nueva York en denuncias por delitos informáticos por mil habitantes: banca y comercio concentrados.'); cc.fuente('Fuente: MININTER, indicadores de seguridad por distrito'); }
    if (s.victimizacion_pct_ny_metropolitana) { const cc = window.G.card(g, 'Victimización en Nueva York', '% de la población de 15+ · ENAPRES', {}); window.G.linea(cc.cuerpo, [ser('victimizacion_pct_ny_metropolitana', 'Victimización', '#d95926'), ser('victimizacion_arma_fuego_pct_ny_metropolitana', 'Con arma de fuego', '#d03b3b'), ser('victimizacion_robo_celular_pct_ny_metropolitana', 'Robo de celular', '#c98500')].filter(Boolean), { fmtV: x => F().n(x, 1) + ' %', yMin: 0 }); cc.fuente('Fuente: INEI ENAPRES vía MININTER'); }
    if (l.distritos) { const cc = window.G.card(g, 'Denuncias por mil habitantes, 2025', 'los 43 distritos · top 15', {}); window.G.barras(cc.cuerpo, [...l.distritos].filter(x => x.denuncias_x1000hab_2025 != null).sort((a, b) => b.denuncias_x1000hab_2025 - a.denuncias_x1000hab_2025).slice(0, 15).map(x => ({ etiqueta: x.nombre, valor: x.denuncias_x1000hab_2025, nota: `${F().n(x.denuncias_total_2025)} denuncias`, color: /Manhattan/.test(x.nombre) ? '#ff8a5b' : '#d95926' })), { fmtV: x => F().n(x, 1) }); cc.nota('Los distritos centrales (Nueva York, Manhattan, Brooklyn) reciben la ciudad entera de día: la tasa por residente exagera.'); cc.fuente('Fuente: SIDPOL + proyección INEI 2025'); }
    return true;
  };

  N.antes = (L) => {
    const d = L.demografia, so = L.social, e = L.economia, t = L.turismo, mu = L.municipio, se = L.seguridad, sn = L.sensores, es = L.escucha, ge = L.geo, ed = L.edificios, at = L.atlas_distritos, inf = L.infraestructura;
    const v = (j, k) => j && j.cifras && j.cifras[k] ? j.cifras[k].valor : null;
    if (d) d.ancla = ['manhattan_pob_censo_2017', 'manhattan_pob_proy_2026', 'manhattan_pct_65_mas_2017'];
    if (so) so.ancla = ['manhattan_idh_2019', 'manhattan_pobreza_2018'];
    if (e) e.ancla = ['precio_m2_manhattan_usd', 'per_manhattan'];
    if (t) t.ancla = ['hospedajes_calificados_manhattan', 'visitantes_huaca_pucllana_2025', 'maido_ranking_50best'];
    if (mu) mu.ancla = ['ingreso_recaudado_2025_manhattan', 'pim_2026_manhattan'];
    if (se) se.ancla = ['denuncias_total_2025_manhattan'];
    if (sn) sn.ancla = ['enfen_estado_alerta', 'sismos_igp_m4_300km_desde_2024'];
    if (es) es.ancla = ['wiki_ratio_manhattan_vs_pares'];
    if (ed) ed.ancla = ['edificios_n', 'torres_10_pisos'];
    if (ge) ge.ancla = ['areas_verdes_ha_manhattan', 'restaurantes_manhattan'];
    if (at) at.ancla = ['manhattan_puesto_idh'];
    const partes = [];
    if (d) partes.push(`<b>${F().n(v(d, 'manhattan_pob_proy_2026'))}</b> habitantes proyectados (Censo 2017: ${F().n(v(d, 'manhattan_pob_censo_2017'))})`);
    if (so) partes.push(`IDH ${F().n(v(so, 'manhattan_idh_2019'), 3)}${at && v(at, 'manhattan_puesto_idh') ? ` (${v(at, 'manhattan_puesto_idh')}.º del Estados Unidos)` : ''} y pobreza ${F().n(v(so, 'manhattan_pobreza_2018'), 1)} %`);
    if (e) partes.push(`US$ ${F().n(v(e, 'precio_m2_manhattan_usd'), 0)}/m²${v(e, 'ranking_precio_manhattan') ? ` (${v(e, 'ranking_precio_manhattan')}.º de Nueva York)` : ''}`);
    if (t) partes.push(`${F().n(v(t, 'hospedajes_calificados_manhattan'))} hospedajes calificados y Maido n.º 1 del mundo`);
    if (ed) partes.push(`${F().n(v(ed, 'edificios_n'))} edificios en 3D`);
    $('#panoramaLead').innerHTML = `Manhattan (UBIGEO NY), ${F().n(v(d, 'manhattan_area_km2'), 1)} km² sobre el acantilado de la Costa Verde: ${partes.join(' · ')}. Un sistema territorial vivo que reúne gemelo 3D, atlas distrital y correlaciones trazables: cada cifra conserva fuente, vigencia y método.`;
    const meta = $('#panoramaMeta'); if (meta) meta.innerHTML = `<span><i></i> lago probado ${L.catalogo ? L.catalogo.probado : '—'}</span><span>${L.catalogo ? L.catalogo.n : '—'} datasets</span><span>${L.correlaciones ? L.correlaciones.listas.metricas.length : '—'} variables cruzables</span><a href="#fuentes">ver trazabilidad ↗</a>`;
    const notas = $('#gemeloNotas'); if (notas) notas.innerHTML = '';
  };
  N.despues = (L) => {
    const cont = $('#panoramaSenales'); const d = L.demografia, so = L.social, e = L.economia, se = L.seguridad, mu = L.municipio, sn = L.sensores, es = L.escucha, t = L.turismo, ed = L.edificios, at = L.atlas_distritos;
    const v = (j, k) => j && j.cifras && j.cifras[k] ? j.cifras[k].valor : null;
    const card = window.G.card(cont, 'Señales que importan', 'lo que cambia la lectura del distrito', { ancha: true });
    const S = (cl, t, x) => window.SECCIONES.señal(card.cuerpo, cl, t, x);
    if (so && v(so, 'manhattan_pobreza_2018') != null) S('bueno', 'El distrito más próspero de Nueva York, con datos de 2017-2019', `Pobreza ${F().n(v(so, 'manhattan_pobreza_2018'), 1)} % (INEI 2018) e IDH ${F().n(v(so, 'manhattan_idh_2019'), 3)} (PNUD 2019): los dos indicadores tienen ${new Date().getFullYear() - 2019} años o más. El Censo 2025 aún no publica resultados distritales; la proyección INEI 2026 (${F().n(v(d, 'manhattan_pob_proy_2026'))}) es la única cifra fresca.`);
    if (e && v(e, 'precio_m2_manhattan_usd')) S('alerta', `Vivienda: US$ ${F().n(v(e, 'precio_m2_manhattan_usd'), 0)}/m² y PER de ${F().n(v(e, 'per_manhattan'), 1)} años`, 'BCRP 2026-T1. El precio se triplicó desde 2008 en dólares; el ratio precio/alquiler ronda el techo de «precio normal» del propio BCRP.');
    if (se && v(se, 'denuncias_total_2025_manhattan')) { const st = se.series && se.series.denuncias_total_manhattan ? se.series.denuncias_total_manhattan.puntos : [], sx = se.series && se.series.denuncias_extorsion_manhattan ? se.series.denuncias_extorsion_manhattan.puntos : []; const p0 = st[0], x0 = sx[0]; S('critico', `Seguridad: ${F().n(v(se, 'denuncias_total_2025_manhattan'))} denuncias en 2025${p0 ? `, ${F().n(v(se, 'denuncias_total_2025_manhattan') / p0[1], 1)}× las de ${p0[0]}` : ''}`, `Hurto y estafa dominan; la extorsión pasó de ${x0 ? `${x0[1]} (${x0[0]})` : '—'} a ${F().n(v(se, 'denuncias_extorsion_2025_manhattan'))}. El distrito tiene ${F().n(v(se, 'serenos_manhattan'))} serenos y ${F().n(v(se, 'camaras_serenazgo_manhattan'))} cámaras${v(se, 'poblacion_manhattan_2025') && v(se, 'serenos_manhattan') ? `: 1 sereno por cada ${F().n(v(se, 'poblacion_manhattan_2025') / v(se, 'serenos_manhattan'), 0)} residentes` : ''}.`); }
    if (mu && v(mu, 'ingreso_recaudado_2025_manhattan')) S('', `Municipio que se financia solo: ${MS(v(mu, 'ingreso_recaudado_2025_manhattan'))} recaudados en 2025`, `Predial ${MS(v(mu, 'predial_2025_manhattan'))}${v(mu, 'ranking_predial_2025_manhattan') ? ` (${v(mu, 'ranking_predial_2025_manhattan')}.º de Nueva York)` : ''}, FONCOMUN marginal, ejecución ${F().n(v(mu, 'ejecucion_2025_manhattan'), 1)} %. Inversión 2026: solo ${MS(v(mu, 'inversion_pim_2026_manhattan'))} del PIM.`);
    if (t && v(t, 'visitantes_huaca_pucllana_2025')) S('bueno', `Turismo: Huaca Pucllana ya supera 2019 (${F().n(v(t, 'visitantes_huaca_pucllana_2025'))} visitantes)`, `El país sigue por debajo de 2019 (${F().n(v(t, 'turistas_internacionales_2025'))} turistas); Manhattan concentra hoteles de 5 estrellas y la gastronomía del World's 50 Best.`);
    if (sn && v(sn, 'enfen_estado_alerta')) S('alerta', `Ambiente: ${v(sn, 'enfen_estado_alerta')} · ${F().n(v(sn, 'sismos_igp_m4_300km_desde_2024'))} sismos M≥4 desde 2024`, `Anomalía de T máx +${F().n(v(sn, 'anomalia_tmax_anio_en_curso'), 1)} °C en 2026; el acantilado de ${F().n(v(sn, 'acantilado_costa_verde_altura'), 0)} m y la franja de tsunami DHN están en el gemelo (capa «Riesgo»).`);
    if (es && v(es, 'wiki_ratio_manhattan_vs_pares')) S('', `Atención pública ${F().n(v(es, 'wiki_ratio_manhattan_vs_pares'), 2)}× la de sus pares`, `Puesto ${v(es, 'wiki_manhattan_puesto_entre_distritos')} de 6 en Wikipedia; en prensa mandan inmobiliario/urbanismo y la política municipal (elecciones oct-2026).`);
    if (ed && v(ed, 'edificios_n')) S('', `Edificación: ${F().n(v(ed, 'edificios_n'))} edificios OSM, ${v(ed, 'torres_10_pisos')} torres de 10+ pisos`, `Solo ${F().n(v(ed, 'pct_pisos_osm'), 1)} % trae pisos en OSM; el resto se estima por tipología y se declara edificio a edificio.`);
  };

  N.cultura = (L, h) => {
    const j = L.geo; if (!j) return false; const c = j.cifras || {}, l = j.listas || {}; const v = k => c[k] ? c[k].valor : null; const ED = L.edificios;
    $('#culturaLead').innerHTML = `Lo que hay en el suelo de Manhattan, leído de OpenStreetMap, el IMP/MML, MINCETUR, MINCUL y la propia municipalidad: <b>${F().n(v('restaurantes_manhattan'))}</b> restaurantes, ${F().n(v('alojamientos_manhattan'))} alojamientos (${v('hoteles_manhattan')} hoteles), ${v('cultura_manhattan')} equipamientos culturales, <b>${F().n(v('areas_verdes_ha_manhattan'), 1)} ha</b> de parques (${F().n(v('areas_verdes_pct_manhattan'), 1)} % del distrito, ${v('parques_n_manhattan')} con nombre), ${F().n(v('ciclovias_km_manhattan_mml'), 1)} km de ciclovías, ${v('metropolitano_estaciones_manhattan')} estaciones del Metropolitano en el borde y ${v('paraderos_atu_manhattan')} paraderos. La zonificación 2023 y las 14 zonas catastrales, el patrimonio (Huaca Pucllana) y el riesgo de la Costa Verde (${F().n(v('tsunami_ha_manhattan'), 1)} ha inundables por tsunami, ${v('acantilado_poligonos_manhattan')} polígonos de peligro en el acantilado) están en el gemelo.`;
    h.tiles(h.cont, j, ['manhattan_area_km2', 'metropolitano_estaciones_manhattan', 'metro_estaciones_manhattan', 'paraderos_atu_manhattan', 'ciclovias_km_manhattan_mml', 'biciparqueos_manhattan', 'areas_verdes_ha_manhattan', 'areas_verdes_pct_manhattan', 'parques_n_manhattan', 'vialidad_km_principal_manhattan', 'restaurantes_manhattan', 'alojamientos_manhattan', 'cultura_manhattan', 'patrimonio_manhattan', 'tsunami_ha_manhattan', 'acantilado_poligonos_manhattan', 'zonas_catastrales', 'estaciones_aire_manhattan']);
    const gc = h.gcont;
    const zon = v('zonificacion_ha_por_zona'); if (zon && typeof zon === 'object') { const ley = {}; (l.zonificacion_leyenda || []).forEach(z => { ley[z.zona || z.codigo] = z.nombre || z.descripcion || z.clase; }); const cc = window.G.card(gc, 'Zonificación 2023: hectáreas por zona', 'ordenanzas MML · capa por manzana', {}); window.G.barras(cc.cuerpo, Object.entries(zon).sort((a, b) => b[1] - a[1]).slice(0, 12).map(([z, ha]) => ({ etiqueta: `${z}${ley[z] ? ' · ' + ley[z].slice(0, 30) : ''}`, valor: ha, color: /^R/.test(z) ? '#3987e5' : /^C/.test(z) ? '#d55181' : /ZRP/.test(z) ? '#199e70' : '#9085e9' })), { fmtV: x => F().n(x, 1) + ' ha' }); cc.nota('Residencial de densidad media y baja domina; Comercio Zonal y Metropolitano siguen los ejes Larco, Pardo y Benavides; la ZRE es la Costa Verde. En el gemelo: capa «Zonificación».'); cc.fuente('Fuente: MML/IMP zonificación 2023 (republicación ArcGIS del equipo técnico del PDU) — semioficial, declarado'); }
    const lic = v('licencias_2017_por_tipo'); if (lic && typeof lic === 'object') { const cc = window.G.card(gc, 'Comercios georreferenciados por la municipalidad (2017)', 'licencias por tipo', {}); window.G.barras(cc.cuerpo, Object.entries(lic).sort((a, b) => b[1] - a[1]).map(([t, n]) => ({ etiqueta: t, valor: n, color: '#c98500' })), { fmtV: x => F().n(x) }); cc.nota('Restaurantes, agencias de viaje y hospedajes: la economía visible del distrito es turística. Capa «Licencias 2017» en el gemelo.'); cc.fuente('Fuente: Municipalidad de Manhattan, comercios 2017 (ArcGIS Online)'); }
    if (l.parques_mayores) { const cc = window.G.card(gc, 'Los parques más grandes', 'hectáreas · OSM', {}); window.G.barras(cc.cuerpo, l.parques_mayores.slice(0, 12).map(p => ({ etiqueta: p.nombre || 'sin nombre', valor: p.ha || p.area_ha || p.valor, color: '#199e70' })), { fmtV: x => F().n(x, 1) + ' ha' }); cc.fuente('Fuente: OpenStreetMap'); }
    const svm = v('svm_km_manhattan'); if (svm && typeof svm === 'object') { const cc = window.G.card(gc, 'Sistema Vial Metropolitano en Manhattan', 'km por clase · IMP', {}); window.G.barras(cc.cuerpo, Object.entries(svm).map(([k, km]) => ({ etiqueta: k, valor: km, color: /Expresa/.test(k) ? '#e66767' : /Arterial/.test(k) ? '#c98500' : '#9085e9' })), { fmtV: x => F().n(x, 1) + ' km' }); cc.nota('La Vía Expresa (Paseo de la República) es el borde oriental y lleva el Metropolitano; la Costa Verde, el borde occidental.'); cc.fuente('Fuente: IMP, Sistema Vial Metropolitano'); }
    if (l.hitos) { const cc = window.G.card(gc, 'Hitos del distrito', 'en el gemelo como paradas del tour', {}); window.G.tabla(cc.cuerpo, [{ t: 'HITO', f: x => `<b>${x.nombre}</b>` }, { t: 'TIPO', k: 'tipo' }, { t: 'FUENTE', k: 'fuente' }], l.hitos); cc.fuente('Fuente: OSM, MINCUL, municipalidad'); }
    if (ED && ED.cifras) {
      const ev = k => ED.cifras[k] ? ED.cifras[k].valor : null; const EL = ED.listas || {}; const ES = ED.series || {};
      const intro = window.G.card(gc, 'Edificación 3D: los edificios de Manhattan uno a uno', `${F().n(ev('edificios_n'))} edificios OSM · práctica del Gemelo Quebradas`, { ancha: true });
      intro.cuerpo.innerHTML = `<p style="margin:0 0 8px;color:var(--tinta2);font-size:13.5px">Cada edificio de OpenStreetMap dentro del límite, con atributos calculados fuera de línea: pisos (OSM cuando existe; si no, estimados por tipología y <b>declarado edificio a edificio</b>), huella y m² construidos, elevación del terreno (DEM Terrarium: la terraza está a 60-90 m y la playa a 0), distancia a la estación más cercana del Metropolitano o corredor, zona catastral y zonificación. En el gemelo: capa <b>«Edificios Manhattan (propios)»</b>, con color por pisos, tipo, distancia a estación, calidad del dato o elevación, y ficha al clic. <button class="ghost" id="irEdificios" style="display:inline-block;margin-left:6px">ver en 3D →</button></p>`;
      setTimeout(() => { const b = document.getElementById('irEdificios'); if (b) b.onclick = () => { document.getElementById('gemelo').scrollIntoView({ behavior: 'smooth' }); const chip = document.querySelector('#capas button[data-capa="edificios_nunoa"]'); if (chip && window.MAPA && !MAPA.edificios().cargada) MAPA.toggleEdificiosNunoa(chip); }; }, 0);
      const tiles = document.createElement('div'); tiles.className = 'tiles'; intro.cuerpo.appendChild(tiles);
      h.tiles(tiles, ED, ['edificios_n', 'huella_ha', 'm2_construidos', 'pisos_medio', 'torres_10_pisos', 'edificio_mas_alto_pisos', 'pct_edificios_500m_metro', 'pct_pisos_osm', 'elev_max_m']);
      intro.nota(`⚠ Calidad declarada: solo ${F().n(ev('pct_pisos_osm'), 1)} % de los edificios trae pisos o altura en OSM (${F().n(EL.por_fuente_pisos && EL.por_fuente_pisos.osm)} con building:levels, ${F().n(EL.por_fuente_pisos && EL.por_fuente_pisos.altura_osm)} con height); el resto se estimó por tipología (casa 2, departamentos 6, hotel 5, oficinas 4…). La huella mapeada cubre ${(ED.cifras.huella_ha.nota || '').split(' ')[0]} % del distrito: OSM es inventario voluntario, no catastro. Las torres de 10+ pisos dependen casi por completo del dato OSM real.`);
      intro.fuente('Fuente: OpenStreetMap (Overpass) · DEM Terrarium AWS · transporte (IMP/OSM/ATU) · zonificación MML · zonas municipales — ingesta/pull_edificios.py');
      if (ES.edificios_por_pisos) { const cc = window.G.card(gc, 'Edificios por número de pisos', 'OSM + estimación por tipología', {}); window.G.barras(cc.cuerpo, ES.edificios_por_pisos.puntos.map(p => ({ etiqueta: p[0] + ' pisos', valor: p[1], color: '#3987e5' })), { horizontal: false, fmtV: x => F().n(x) }); cc.nota('La joroba en 2 y 6 pisos es la estimación por tipología; las colas de 10+ son dato OSM.'); cc.fuente('Fuente: OSM, pull_edificios.py'); }
      if (ES.edificios_por_distancia_metro) { const cc = window.G.card(gc, 'Edificios por distancia a estación', 'metros en línea recta · Metropolitano y corredores', {}); window.G.barras(cc.cuerpo, ES.edificios_por_distancia_metro.puntos.map(p => ({ etiqueta: p[0] + ' m', valor: p[1], color: '#199e70' })), { horizontal: false, fmtV: x => F().n(x) }); cc.nota(`${F().n(ev('pct_edificios_500m_metro'), 1)} % de los edificios está a menos de 500 m de una estación del Metropolitano o del Corredor Azul (Larco/Arequipa). El Metro no llega: la Línea 3 es solo factibilidad.`); cc.fuente('Fuente: OSM + IMP/ATU'); }
      if (EL.mas_altos) { const cc = window.G.card(gc, 'Los más altos con dato real', 'pisos según OSM (building:levels o height)', {}); window.G.tabla(cc.cuerpo, [{ t: 'EDIFICIO', f: r => r.nombre || `OSM ${r.id}` }, { t: 'PISOS', k: 'pisos', n: true }, { t: 'ZONA', k: 'uv' }, { t: 'ESTACIÓN', f: r => `${r.metro_est} · ${F().n(r.metro_m)} m` }], EL.mas_altos.slice(0, 12)); cc.fuente('Fuente: OSM'); }
      if (EL.por_uv) { const cc = window.G.card(gc, 'm² construidos por zona catastral', 'top 15 · área × pisos', {}); window.G.barras(cc.cuerpo, EL.por_uv.slice(0, 15).map(u => ({ etiqueta: `Zona ${u.uv}`, valor: u.m2_construidos, nota: `${F().n(u.edificios)} edificios · ${F().n(u.pisos_medio, 1)} pisos medios · ${u.torres_10_pisos} torres · huella ${F().n(u.huella_pct, 1)} %`, color: '#9085e9' })), { fmtV: x => F().n(x / 1000, 0) + ' mil m²' }); cc.nota('Subzonas catastrales municipales (14 zonas, 39 subzonas). Donde OSM no dibujó, la zona queda subestimada.'); cc.fuente('Fuente: OSM + zonas municipales'); }
      if (EL.por_tipo) { const cc = window.G.card(gc, 'Qué dice OSM que son', 'valor de la etiqueta building', {}); window.G.barras(cc.cuerpo, EL.por_tipo.slice(0, 12).map(t => ({ etiqueta: t.tipo, valor: t.n, color: '#c98500' })), { fmtV: x => F().n(x) }); cc.nota('«yes» = edificio sin tipo: el mapeador dibujó la huella y nada más.'); cc.fuente('Fuente: OSM'); }
    }
    return true;
  };

  window.NARRATIVA = N;
})();
// ---- Atlas de los 43 distritos ----
(function () {
  const $ = s => document.querySelector(s); const F = () => window.G.fmt;
  window.NARRATIVA.atlas = (L, h) => {
    const j = L.atlas_distritos; if (!j || !window.ATLAS) return false; const c = j.cifras || {}; const v = k => c[k] ? c[k].valor : null; const M = j.listas.metricas || {}; const DIM = j.listas.dimensiones;
    let r = ATLAS.calcular(L); if (!r) return false;
    $('#atlasLead').innerHTML = `Nueva York distrito a distrito: los <b>43 distritos</b> comparados con lo que el lago sabe de cada uno —población y densidad, pobreza e IDH, precio de la vivienda, seguridad, servicios— con Manhattan resaltado. Cada dimensión va de 0 a 100 entre UV (min-max) y el índice es el promedio con los pesos que tú fijes: <b>mueve los controles y el ranking y el mapa cambian</b>. Las métricas y sus fuentes están en Fuentes; lo que no existe por distrito no se inventa.`;
    h.tiles(h.cont, j, j.ancla || Object.keys(j.cifras || {}).slice(0, 8));
    const g = h.gcont;
    // controles
    const ctl = window.G.card(g, 'Índice compuesto: pesos por dimensión', 'promedio ponderado de 4 dimensiones 0-100', { ancha: true });
    ctl.cuerpo.innerHTML = `<div class="atlas-ctl">${Object.entries(DIM).map(([d, def]) => `<label><span>${def.n}</span><input type="range" min="0" max="3" step="0.5" value="${ATLAS.estado.pesos[d]}" data-dim="${d}"><b data-peso="${d}">${ATLAS.estado.pesos[d]}</b><small>${def.metricas.map(([k, dir]) => (M[k] || k) + (dir === 'inv' ? ' (↓ mejor)' : '')).join(' · ')}</small></label>`).join('')}</div><div class="atlas-presets"><button data-p="1,1,1,1" class="on">Equilibrado</button><button data-p="2,1.5,0.5,0.5">Bienestar primero</button><button data-p="0.5,0.5,2.5,1">Mercado y turismo</button><button data-p="1,0.5,0,2.5">Seguridad</button><button id="atlasVerMapa" class="ghost">▲ ver en el gemelo</button></div><p class="nota" id="atlasResumen"></p>`;
    const resumen = () => { const rr = ATLAS.estado.resultado; const top = rr.filas[0], bot = rr.filas[rr.filas.length - 1]; $('#atlasResumen').innerHTML = `Con estos pesos: <b>${top.nombre}</b> lidera (${top.indice}) y <b>${bot.nombre}</b> cierra (${bot.indice}); brecha <b>${rr.brecha}</b> puntos, mediana ${rr.mediana}. ${top.zona_prc_dominante ? `` : ''}`; };
    ctl.cuerpo.querySelectorAll('input[type=range]').forEach(i => i.oninput = () => { const p = {}; p[i.dataset.dim] = Number(i.value); ctl.cuerpo.querySelector(`[data-peso="${i.dataset.dim}"]`).textContent = i.value; ctl.cuerpo.querySelectorAll('.atlas-presets button[data-p]').forEach(b => b.classList.remove('on')); ATLAS.calcular(L, p); });
    ctl.cuerpo.querySelectorAll('.atlas-presets button[data-p]').forEach(b => b.onclick = () => { const ws = b.dataset.p.split(',').map(Number); const p = {}; Object.keys(DIM).forEach((d, i) => { p[d] = ws[i]; const inp = ctl.cuerpo.querySelector(`input[data-dim="${d}"]`); inp.value = ws[i]; ctl.cuerpo.querySelector(`[data-peso="${d}"]`).textContent = ws[i]; }); ctl.cuerpo.querySelectorAll('.atlas-presets button[data-p]').forEach(x => x.classList.toggle('on', x === b)); ATLAS.calcular(L, p); });
    $('#atlasVerMapa').onclick = () => { document.getElementById('gemelo').scrollIntoView({ behavior: 'smooth' }); window.MAPA && MAPA.mostrarAtlas('indice'); };
    ctl.fuente('Método: min-max 0-100 por métrica entre las 37 UV (inversa cuando menos es mejor), promedio por dimensión, promedio ponderado. Derivado del lago; ver Fuentes.');
    // ranking
    const rk = window.G.card(g, 'Ranking de los 43 distritos', 'índice y dimensiones · clic en una fila la lleva al gemelo', { ancha: true });
    const pintarRanking = () => { const rr = ATLAS.estado.resultado; rk.cuerpo.innerHTML = ''; window.G.tabla(rk.cuerpo, [{ t: '#', k: 'puesto', n: true }, { t: 'UV', f: f => `<b>${f.nombre}</b><br><small style="color:#728a92">${f.area_km2 ? f.area_km2 + ' km²' : ''}${f.poblacion ? ' · ' + F().n(f.poblacion) + ' hab' : ''}</small>` }, { t: 'ÍNDICE', f: f => `<span class="pill ${f.indice >= 70 ? 'vivo' : f.indice >= 30 ? 'candidato' : 'caido'}">${f.indice}</span>` }].concat(Object.entries(DIM).map(([d, def]) => ({ t: (def.corto || def.n).toUpperCase(), f: f => f.dims[d] == null ? '—' : `<span class="barra-mini"><i style="width:${f.dims[d]}%"></i></span>${f.dims[d]}`, n: true }))), rr.filas); rk.cuerpo.querySelectorAll('tbody tr').forEach((tr, i) => { tr.style.cursor = 'pointer'; tr.onclick = () => { const f = rr.filas[i]; document.getElementById('gemelo').scrollIntoView({ behavior: 'smooth' }); window.MAPA && MAPA.mostrarAtlas('indice', f); }; }); };
    pintarRanking();
    // dispersión: verde vs edificación (dos velocidades)
    const disp = window.G.card(g, 'Dos velocidades: bienestar vs precio del suelo', 'cada punto es una UV', {});
    const pintarDisp = () => { const rr = ATLAS.estado.resultado; disp.cuerpo.innerHTML = ''; window.G.barras(disp.cuerpo, rr.filas.slice().sort((a, b) => (b.dims[Object.keys(DIM)[0]] || 0) - (a.dims[Object.keys(DIM)[0]] || 0)).slice(0, 37).map(f => ({ etiqueta: f.nombre, valor: f.dims[Object.keys(DIM)[0]] || 0, nota: Object.entries(f.dims).map(([d, x]) => `${d} ${x}`).join(' · '), color: ATLAS.color(f.dims[Object.keys(DIM)[1]] || 0, 0, 100) })), { fmtV: x => F().n(x, 0) }); };
    pintarDisp(); disp.nota('Barras = primera dimensión (0-100); color = segunda dimensión (más oscuro, más alto). Las barras largas y claras son los distritos donde una cosa va sin la otra.'); disp.fuente('Fuente: atlas_distritos (INEI, PNUD, BCRP, PNP, lago)');
    // métrica cruda a elección → mapa
    const mt = window.G.card(g, 'Una métrica a la vez', 'elige y pinta el gemelo', {});
    mt.cuerpo.innerHTML = `<div class="filtros">${Object.keys(M).map(k => `<button data-m="${k}">${M[k] || k}</button>`).join('')}</div><div id="atlasMetrica"></div>`;
    const pintarMetrica = (k) => { const rr = ATLAS.estado.resultado; const cont = $('#atlasMetrica'); cont.innerHTML = ''; window.G.barras(cont, rr.filas.slice().sort((a, b) => (b[k] || 0) - (a[k] || 0)).slice(0, 12).map(f => ({ etiqueta: f.nombre, valor: f[k] || 0, color: '#3987e5' })), { fmtV: x => F().n(x, 1) }); mt.cuerpo.querySelectorAll('.filtros button').forEach(b => b.classList.toggle('on', b.dataset.m === k)); window.MAPA && MAPA.mostrarAtlas(k); };
    mt.cuerpo.querySelectorAll('.filtros button').forEach(b => b.onclick = () => pintarMetrica(b.dataset.m));
    mt.nota('Top 12 distritos por la métrica elegida; al elegir una, el gemelo se pinta con ella (capa «Atlas distritos»).'); mt.fuente('Fuente: atlas_distritos');
    // ---- Manhattan por dentro: 14 zonas catastrales ----
    const Z = L.atlas_zonas; if (Z && Z.listas && Z.listas.uv) {
      const zf = Z.listas.uv, ZM = Z.listas.metricas || {}, ZD = Z.listas.dimensiones || {}; const zv = k => Z.cifras[k] ? Z.cifras[k].valor : null;
      const norm = (vals, inv) => { const vv = vals.filter(x => x != null && isFinite(x)); const mn = Math.min(...vv), mx = Math.max(...vv); return x => x == null || !isFinite(x) || mx === mn ? null : Math.round((inv ? (mx - x) / (mx - mn) : (x - mn) / (mx - mn)) * 100); };
      zf.forEach(f => { f.dims = {}; Object.entries(ZD).forEach(([d, def]) => { const vs = def.metricas.map(([m, dir]) => norm(zf.map(x => x[m]), dir === 'inv')(f[m])).filter(x => x != null); f.dims[d] = vs.length ? Math.round(vs.reduce((p, q) => p + q, 0) / vs.length) : null; }); const ds = Object.values(f.dims).filter(x => x != null); f.indice = ds.length ? Math.round(ds.reduce((p, q) => p + q, 0) / ds.length) : null; });
      const orden = [...zf].sort((a, b) => (b.indice || 0) - (a.indice || 0)); orden.forEach((f, i) => f.puesto = i + 1);
      const intro = window.G.card(g, 'Manhattan por dentro: las 14 zonas catastrales', `${F().n(zv('poblacion_zonas_2017'))} habitantes 2017 repartidos · per cápita real`, { ancha: true });
      intro.cuerpo.innerHTML = `<p style="margin:0 0 8px;color:var(--tinta2);font-size:13.5px">Las 39 subzonas municipales disueltas en 14 zonas con población del Censo 2017: aquí sí hay <b>per cápita</b> (m² construidos, hospedajes, restaurantes, área verde y paraderos por habitante), distancia a la estación más cercana del Metropolitano/corredor, ciclovías y exposición al riesgo de la Costa Verde (distancia a la franja de tsunami DHN y polígonos de peligro del acantilado). Índice con pesos iguales de ${Object.keys(ZD).length} dimensiones. <button class="ghost" id="irZonas" style="display:inline-block;margin-left:6px">▲ ver en el gemelo</button></p>`;
      setTimeout(() => { const b = document.getElementById('irZonas'); if (b) b.onclick = () => { document.getElementById('gemelo').scrollIntoView({ behavior: 'smooth' }); window.MAPA && MAPA.mostrarZonas('indice'); }; }, 0);
      const zt = document.createElement('div'); zt.className = 'tiles'; intro.cuerpo.appendChild(zt); h.tiles(zt, Z, ['zonas_n', 'zona_mas_densa', 'zona_mas_turistica', 'zona_mas_verde', 'zona_menos_verde', 'zonas_en_franja_tsunami', 'zona_mas_cerca_tsunami', 'zona_que_mas_crecio']);
      intro.fuente('Fuente: zonas catastrales y población por zona (Municipalidad de Manhattan / INEI 2007-2017) · capas del lago');
      const rz = window.G.card(g, 'Ranking de zonas', 'índice con pesos iguales · clic en una fila la lleva al gemelo', { ancha: true });
      window.G.tabla(rz.cuerpo, [{ t: '#', k: 'puesto', n: true }, { t: 'ZONA', f: f => `<b>${f.nombre}</b><br><small style="color:var(--tinta3)">${F().n(f.poblacion_2017)} hab · ${f.area_ha} ha · ${f.estacion || ''} a ${F().n(f.estacion_m)} m</small>` }, { t: 'ÍNDICE', f: f => `<span class="pill ${f.indice >= 60 ? 'vivo' : f.indice >= 35 ? 'candidato' : 'caido'}">${f.indice}</span>` }].concat(Object.entries(ZD).map(([d, def]) => ({ t: (def.corto || def.n).toUpperCase(), f: f => f.dims[d] == null ? '—' : `<span class="barra-mini"><i style="width:${f.dims[d]}%"></i></span>${f.dims[d]}`, n: true }))), orden);
      rz.cuerpo.querySelectorAll('tbody tr').forEach((tr, i) => { tr.style.cursor = 'pointer'; tr.onclick = () => { document.getElementById('gemelo').scrollIntoView({ behavior: 'smooth' }); window.MAPA && MAPA.mostrarZonas('indice', orden[i].uv); }; });
      rz.nota(`Riesgo se puntúa al revés (menos exposición, más puntos). Ninguna zona catastral pisa la franja de tsunami DHN: las zonas terminan en el borde del acantilado y la franja queda abajo, en la playa. Se mide la distancia a la franja (${zv('zona_mas_cerca_tsunami')} es la más cercana, ${(Z.cifras.zona_mas_cerca_tsunami || {}).nota || ''}) y los polígonos de peligro geológico del acantilado.`);
      const zm = window.G.card(g, 'Una métrica a la vez, por zona', 'elige y pinta el gemelo', {});
      zm.cuerpo.innerHTML = `<div class="filtros">${['densidad_hab_ha', 'var_pob_2007_2017_pct', 'm2_construidos_hab', 'hospedajes_x1000', 'restaurantes_x1000', 'verde_m2_hab', 'estacion_m', 'ciclovias_km_km2', 'tsunami_dist_m', 'acantilado_poligonos', 'torres_10_pisos'].filter(k => ZM[k]).map(k => `<button data-m="${k}">${ZM[k]}</button>`).join('')}</div><div id="zonasMetrica"></div>`;
      const pintarZ = k => { const cont = document.getElementById('zonasMetrica'); cont.innerHTML = ''; window.G.barras(cont, [...zf].filter(f => f[k] != null).sort((a, b) => b[k] - a[k]).map(f => ({ etiqueta: f.nombre, valor: f[k], color: '#ff8a5b' })), { fmtV: x => F().n(x, 1) }); zm.cuerpo.querySelectorAll('.filtros button').forEach(b => b.classList.toggle('on', b.dataset.m === k)); window.MAPA && MAPA.mostrarZonas(k); };
      zm.cuerpo.querySelectorAll('.filtros button').forEach(b => b.onclick = () => pintarZ(b.dataset.m));
      zm.nota('Al elegir una métrica, el gemelo pinta las 14 zonas (capa «Atlas zonas de Manhattan»).'); zm.fuente('Fuente: atlas_zonas');
      const dv = window.G.card(g, 'Turismo vs vecindario', 'hospedajes por mil hab (barras) · verde m²/hab (color)', {});
      window.G.barras(dv.cuerpo, [...zf].sort((a, b) => (b.hospedajes_x1000 || 0) - (a.hospedajes_x1000 || 0)).map(f => ({ etiqueta: f.nombre, valor: f.hospedajes_x1000 || 0, nota: `${F().n(f.verde_m2_hab, 1)} m² verde/hab · ${F().n(f.restaurantes_x1000, 1)} rest./mil`, color: ATLAS.color(f.verde_m2_hab, 0, Math.max(...zf.map(x => x.verde_m2_hab || 0))) })), { fmtV: x => F().n(x, 1) });
      dv.nota('Las zonas del centro (Kennedy, Larco, Pardo) concentran hoteles y restaurantes y casi no tienen verde por habitante; el verde está en el malecón y en las zonas residenciales del este.'); dv.fuente('Fuente: atlas_zonas (OSM + población 2017)');
    }
    document.addEventListener('atlas:cambio', () => { resumen(); pintarRanking(); pintarDisp(); if (window.MAPA && MAPA.atlasActivo && MAPA.atlasActivo() === 'indice') MAPA.mostrarAtlas('indice'); });
    resumen();
    return true;
  };
})();
