"""Catálogo de fuentes: única fuente de verdad para lago/catalogo.json y la hoja «1. Fuentes» del Excel.

Columnas = las de la plantilla del taller. La licencia se copia tal como la declara la fuente; si el dataset
no trae licencia en sus metadatos se escribe «no declara» y en observaciones se explica el marco del portal.
"""

LICENCIA_NYC = ('no declara (el dataset no trae campo de licencia; el portal se rige por los Términos de Uso de NYC.gov '
                'y la Local Law 11 de 2012, que obliga a publicar sin registro ni restricciones de uso)')

_NYC_OBS = ' Licencia: el dataset no la declara en sus metadatos (verificado en /api/views/{id}.json); el portal NYC Open Data se rige por la Local Law 11 de 2012 y los Términos de Uso de NYC.gov.'
_NYS_OBS = ' Licencia: el dataset no la declara; data.ny.gov se rige por los Términos de Uso de Open NY.'

C = ['id', 'nombre', 'entidad', 'tipo_publicador', 'url', 'formato', 'como_se_obtiene', 'licencia', 'personas',
     'cobertura', 'periodo', 'frecuencia', 'fecha_prueba', 'estado', 'como_la_encontraron', 'observaciones', 'lago']


def F(*v):
    return dict(zip(C, v))


P = '2026-10-04'   # día en que la API respondió de verdad al correr scripts/construir_lago.py
NYC = 'https://data.cityofnewyork.us/resource/'

FUENTES = [
    F('F02', 'Motor Vehicle Collisions - Crashes', 'NYC Police Department (NYPD)', 'Entidad pública', NYC + 'h9gi-nx95.json', 'JSON', 'API sin llave',
      'no declara', 'No', 'Ciudad de NY, borough y lat/lon del choque', '2012 a hoy (se usa 2025 completo)', 'Diaria', P, 'Integrada al lago',
      'Ya estaba en la primera versión del lago; re-verificada por API el 2026-10-04',
      'Se descargan solo conteos y coordenadas. Los choques sin borough se ubican por coordenadas contra los PUMA oficiales (F19).' + _NYC_OBS.format(id='h9gi-nx95'),
      'seguridad_vial.json, distritos.json'),
    F('F03', '311 Service Requests from 2020 to Present', 'NYC Office of Technology and Innovation (OTI) / NYC311', 'Entidad pública', NYC + 'erm2-nwe9.json', 'JSON', 'API sin llave',
      'no declara', 'Texto libre sin revisar', 'Ciudad de NY, borough, distrito comunitario, tipo y coordenada', '2020 a hoy (se usa 2025 completo)', 'Diaria', P, 'Integrada al lago',
      'Ya estaba en la primera versión del lago; re-verificada por API el 2026-10-04',
      'Más de 40 millones de filas: la consulta anual agregada agota el tiempo de la API, se consulta mes a mes. La fuente trae dirección exacta y descriptor en texto libre; el lago solo guarda conteos por borough, distrito y tipo. El nombre del dataset cambió de "from 2010" a "from 2020".' + _NYC_OBS.format(id='erm2-nwe9'),
      'calidad_de_vida_311.json, distritos.json'),
    F('F04', 'NYPD Complaint Data Historic', 'NYC Police Department (NYPD)', 'Entidad pública', NYC + 'qgea-i56i.json', 'JSON', 'API sin llave',
      'no declara', 'Personas identificables', 'Ciudad de NY, borough, precinto y lat/lon', '2006 a 2025 (se usa año de reporte 2025)', 'Anual', P, 'Integrada al lago',
      'Claude Code propuso pasar del dataset del año en curso (F14) al histórico para tener 2025 completo; verificada por API',
      'Trae edad, raza y sexo de víctima y sospechoso más coordenadas: combinados pueden reidentificar a una víctima. En el lago solo quedan conteos por borough, categoría legal y distrito.' + _NYC_OBS.format(id='qgea-i56i'),
      'seguridad_delitos.json, distritos.json'),
    F('F05', 'DOB NOW: Build – Job Application Filings', 'NYC Department of Buildings (DOB)', 'Entidad pública', NYC + 'w9ak-ipjd.json', 'JSON', 'API sin llave',
      'no declara', 'Personas identificables', 'Ciudad de NY, borough, distrito comunitario, BBL y lat/lon', '2016 a hoy (se usan radicaciones de obra nueva 2025)', 'Diaria', P, 'Integrada al lago',
      'Encontrada con Claude Code en el catálogo (API de catálogo de Socrata) al descartar el sistema legado (F23)',
      'SENSIBLE: nombres de propietario, solicitante y gestor, licencia profesional y dirección comercial. No se descargan. Calidad: cada obra repite sus viviendas en cada trámite (-P1, -S8…); se cuenta solo la radicación inicial (-I1).' + _NYC_OBS.format(id='w9ak-ipjd'),
      'vivienda.json, distritos.json'),
    F('F06', 'Film Permits', "NYC Mayor's Office of Media and Entertainment (MOME)", 'Entidad pública', NYC + 'tg4x-b46p.json', 'JSON', 'API sin llave',
      'no declara', 'No', 'Ciudad de NY, borough, distrito comunitario y precinto', '2012 a hoy (se usa 2025)', 'Diaria', P, 'Integrada al lago',
      'Ya estaba en la primera versión del lago; re-verificada por API el 2026-10-04',
      'En el histórico hay filas con valores en "borough" que no son boroughs (p. ej. "Shooting Permit"); el script las cuenta aparte (en 2025 no apareció ninguna).' + _NYC_OBS.format(id='tg4x-b46p'),
      'economia_rodajes.json'),
    F('F07', '2015 Street Tree Census - Tree Data', 'NYC Department of Parks and Recreation', 'Entidad pública', NYC + 'uvpi-gqnh.json', 'JSON', 'API sin llave',
      'no declara', 'No', 'Árboles de calle de NYC, lat/lon y distrito comunitario', 'Censo 2015', 'Única vez', P, 'Integrada al lago',
      'Ya estaba en la primera versión del lago; re-verificada por API el 2026-10-04',
      'Dato de 2015: referencia estructural, no estado actual. El censo 2025 aún no está publicado como dataset.' + _NYC_OBS.format(id='uvpi-gqnh'),
      'ambiente.json, distritos.json'),
    F('F08', "Wikimedia Pageviews: artículos 'New York City', 'Nueva York' y los 5 boroughs", 'Wikimedia Foundation', 'Plataforma colaborativa',
      'https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/user/New_York_City/monthly/2024100100/2026093000', 'JSON', 'API sin llave',
      'CC0', 'No', 'Artículo de la ciudad y de cada borough (interés global)', '2024-10 a 2026-09', 'Mensual', P, 'Integrada al lago',
      'Ya estaba en la primera versión (misma familia que el ejemplo F01); ampliada con Claude Code a los boroughs y al artículo en español',
      "Cuenta vistas de personas (agente 'user'), excluye bots. Mide interés, no opinión.", 'escucha_interes.json'),
    F('F09', 'Censo 2020: población por borough', 'U.S. Census Bureau / NYC Department of City Planning (DCP)', 'Entidad pública',
      'https://www.nyc.gov/content/planning/pages/planning/nyc-population-2020-census', 'XLSX', 'Solo PDF o página',
      'no declara', 'No', '5 boroughs', '1 de abril de 2020', 'Única vez', P, 'Integrada al lago',
      'Cifras oficiales del DCP, contrastadas con la fuente F25 (que resultó ser una proyección)',
      'La página es dinámica (no se deja descargar con un script), por eso las cinco cifras se transcriben en el código y quedan marcadas como transcritas. Obra del gobierno federal: dominio público (17 U.S.C. §105).',
      'demografia.json'),
    F('F10', 'American Community Survey 2020–2024, 5 años (tablas B01003, B19013, B25064, B25070, B25071, B17001, B25003, B08301, B08201, B05002, B03002, B01002)',
      'U.S. Census Bureau, servido por Census Reporter (Knight Lab, Northwestern University)', 'Academia u ONG',
      'https://api.censusreporter.org/1.0/data/show/acs2024_5yr?table_ids=B19013&geo_ids=05000US36061', 'JSON', 'API sin llave',
      'no declara', 'No', '5 condados y 55 PUMA de NYC', '2020–2024 (dólares de 2024)', 'Anual', P, 'Integrada al lago',
      'Claude Code propuso la API oficial del Censo (F21); como exige llave, se usó este espejo académico (ver Bitácora)',
      'Reemplaza al informe en PDF del Contralor: las cifras de ingreso 2024 que usaba el prototipo eran en realidad estas del ACS. Census Reporter no declara licencia; los datos son del Census Bureau, de dominio público. Cada cifra trae margen de error al 90 %.',
      'demografia.json, distritos.json'),
    F('F11', 'ACRIS - Real Property Master', 'NYC Department of Finance (DOF)', 'Entidad pública', NYC + 'bnx9-e6tj.json', 'JSON', 'API sin llave',
      'no declara', 'No', 'Ciudad de NY, borough codificado 1–5', 'Histórico de documentos', 'Mensual', P, 'Candidata',
      'Ya estaba en la primera versión del lago; re-verificada por API el 2026-10-04',
      'No integrada: de las escrituras (DEED) de 2025 cerca de 4 de cada 10 traen monto 0 y el 94 % aparece en Manhattan (distribución inverosímil, sin explicar) y la tabla ACRIS-Parties (nombres de compradores y vendedores) se evita por minimización. Para usarla habría que cruzar con Rolling Sales del DOF.' + _NYC_OBS.format(id='bnx9-e6tj'),
      'verificaciones.json'),
    F('F12', 'NYPD Calls for Service (Year to Date)', 'NYC Police Department (NYPD)', 'Entidad pública', NYC + 'n2zq-pubd.json', 'JSON', 'API sin llave',
      'no declara', 'Solo conteos por zona', 'Ciudad de NY, por precinto', 'Año en curso', 'Trimestral', P, 'Descartada',
      'Ya estaba en la primera versión del lago; re-verificada por API el 2026-10-04',
      'Descartada por redundancia: mide llamadas al 911, no delitos confirmados, y se solapa con F04 y con 311; sumarla produciría doble conteo.' + _NYC_OBS.format(id='n2zq-pubd'),
      'verificaciones.json'),
    F('F14', 'NYPD Complaint Data Current (Year To Date)', 'NYC Police Department (NYPD)', 'Entidad pública', NYC + '5uac-w243.json', 'JSON', 'API sin llave',
      'no declara', 'Personas identificables', 'Ciudad de NY, borough y lat/lon', 'Año en curso (2026, hasta el último trimestre publicado)', 'Trimestral', P, 'Integrada al lago',
      'Era la fuente F04 de la primera versión del lago; re-verificada por API el 2026-10-04',
      'Se usa solo para comparar enero–junio 2026 contra enero–junio 2025 (F04). Calidad: trae fechas de inicio en el año 1016.' + _NYC_OBS.format(id='5uac-w243'),
      'seguridad_delitos.json'),
    F('F15', 'Air Quality (NYC Community Air Survey)', 'NYC Department of Health and Mental Hygiene (DOHMH)', 'Entidad pública', NYC + 'c3uy-2p5r.json', 'JSON', 'API sin llave',
      'no declara', 'No', 'Ciudad, borough, distrito comunitario, UHF', '2009 a 2024', 'Anual', P, 'Integrada al lago',
      'Propuesta por Claude Code para la sección de ambiente; verificada por API',
      'Cada año trae media anual, de verano y de invierno con la misma etiqueta de periodo: se filtra measure = "Annual mean".' + _NYC_OBS.format(id='c3uy-2p5r'),
      'ambiente.json, distritos.json'),
    F('F16', 'Affordable Housing Production by Building (Housing New York)', 'NYC Department of Housing Preservation and Development (HPD)', 'Entidad pública', NYC + 'hg8x-zxpr.json', 'JSON', 'API sin llave',
      'no declara', 'No', 'Ciudad de NY, edificio, borough, distrito comunitario', '2014 a hoy', 'Trimestral', P, 'Integrada al lago',
      'Propuesta por Claude Code al buscar vivienda asequible por distrito; verificada por API',
      'Responde la pregunta de vivienda que la versión anterior dejaba sin datos.' + _NYC_OBS.format(id='hg8x-zxpr'),
      'vivienda.json, distritos.json'),
    F('F17', 'MTA Daily Ridership and Traffic: Beginning 2020', 'Metropolitan Transportation Authority (MTA)', 'Entidad pública', 'https://data.ny.gov/resource/sayj-mze2.json', 'JSON', 'API sin llave',
      'no declara', 'No', 'Red MTA (subte, bus, trenes, puentes y túneles, zona de congestión)', '2020-03 a hoy', 'Diaria', P, 'Integrada al lago',
      'Encontrada con Claude Code en el catálogo (API de catálogo de Socrata) de data.ny.gov al detectar que F22 estaba desactualizada',
      'Incluye ingresos a la zona de cobro por congestión desde enero de 2025.' + _NYS_OBS, 'movilidad.json'),
    F('F18', 'MTA Subway Stations', 'Metropolitan Transportation Authority (MTA)', 'Entidad pública', 'https://data.ny.gov/resource/39hk-dx4f.json', 'JSON', 'API sin llave',
      'no declara', 'No', 'Estaciones con borough, líneas, accesibilidad y coordenadas', 'Vigente', 'No se sabe', P, 'Integrada al lago',
      'Fuente oficial que reemplaza la copia de GitHub (kevin-brown/nyc-open-geojson) que usaba el prototipo',
      'Una fila por estación-línea (496 con el ferrocarril de Staten Island); la MTA comunica 472 estaciones de subte.' + _NYS_OBS, 'geo/estaciones.geojson, demografia.json'),
    F('F19', '2020 Public Use Microdata Areas (PUMAs)', 'NYC Department of City Planning (DCP)', 'Entidad pública', NYC.replace('resource/', 'resource/') + 'pikk-p9nv.geojson', 'GeoJSON', 'API sin llave',
      'no declara', 'No', '55 PUMA de NYC', 'Geografía 2020', 'Trimestral', P, 'Integrada al lago',
      'Encontrada con Claude Code en el catálogo (API de catálogo de Socrata); la equivalencia PUMA–distrito comunitario se comprobó con los 55 nombres del ACS',
      'Unidad del atlas y de las correlaciones (n = 55). Se simplifican a ~20 m para el mapa.' + _NYC_OBS.format(id='pikk-p9nv'),
      'geo/distritos_puma.geojson'),
    F('F20', 'Borough Boundaries', 'NYC Department of City Planning (DCP)', 'Entidad pública', NYC + 'gthc-hcne.geojson', 'GeoJSON', 'API sin llave',
      'no declara', 'No', '5 boroughs (recortados a la costa)', 'Vigente', 'Trimestral', P, 'Integrada al lago',
      'Fuente oficial que reemplaza la copia de click_that_hood (GitHub) que usaba el prototipo',
      'De aquí sale la superficie terrestre de cada borough.' + _NYC_OBS.format(id='gthc-hcne'), 'geo/boroughs.geojson'),
    F('F21', 'Census Data API (api.census.gov)', 'U.S. Census Bureau', 'Entidad pública', 'https://api.census.gov/data/2024/acs/acs5?get=NAME,B19013_001E&for=county:061&in=state:36', 'JSON', 'API con llave gratuita',
      'no declara', 'No', 'EE. UU. (todas las geografías)', '2005 a hoy', 'Anual', P, 'Descartada',
      'Claude Code la propuso como fuente primaria del ACS',
      'Sin llave responde 302 hacia /data/missing_key.html. La llave es gratuita pero exige registro con correo; para que el lago se pueda reconstruir sin secretos se usó F10 y se verificó que las cifras coinciden.',
      'verificaciones.json'),
    F('F22', 'MTA Daily Ridership Data: 2020 - 2025', 'Metropolitan Transportation Authority (MTA)', 'Entidad pública', 'https://data.ny.gov/resource/vxuj-8kew.json', 'JSON', 'API sin llave',
      'no declara', 'No', 'Red MTA', '2020-03 a 2025-01-09', 'No se sabe', P, 'Descartada',
      'Primer resultado al buscar "ridership" en el catálogo de data.ny.gov',
      'Dato viejo: su última fecha es 9-ene-2025. Se reemplazó por F17.' + _NYS_OBS, 'verificaciones.json'),
    F('F23', 'DOB Job Application Filings (sistema legado BIS)', 'NYC Department of Buildings (DOB)', 'Entidad pública', NYC + 'ic3t-wcy2.json', 'JSON', 'API sin llave',
      'no declara', 'Personas identificables', 'Ciudad de NY', '1989 a hoy', 'Diaria', P, 'Descartada',
      'Era la fuente F05 de la primera versión del lago; re-verificada por API el 2026-10-04',
      'Sistema en retiro: casi todas las obras se radican hoy en DOB NOW (F05). Además sus fechas son texto MM/DD/AAAA, así que un filtro de fecha normal devuelve 0 filas sin avisar. Trae nombres de propietarios.' + _NYC_OBS.format(id='ic3t-wcy2'),
      'verificaciones.json'),
    F('F24', 'Open-Meteo Forecast API (tiempo actual en Manhattan)', 'Open-Meteo', 'Empresa privada', 'https://api.open-meteo.com/v1/forecast?latitude=40.7831&longitude=-73.9712&current=temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code', 'JSON', 'API sin llave',
      'CC BY 4.0', 'No', 'Punto en Central Park', 'Tiempo real', 'Tiempo real', P, 'Integrada al lago',
      'Misma fuente del clima en vivo del Cerebro Lima', 'Se consulta desde el navegador; no se guarda en el lago.', '(en vivo, sitio web)'),
    F('F25', 'New York City Population by Borough, 1950 - 2040', 'NYC Department of City Planning (DCP)', 'Entidad pública', NYC + 'xywu-7bv9.json', 'JSON', 'API sin llave',
      'no declara', 'No', '5 boroughs', '1950–2040', 'Única vez', P, 'Descartada',
      'Claude Code la encontró en el catálogo como "población 2020 por API"',
      'La columna 2020 dice 8.550.971: es una proyección hecha en 2013, no el Censo 2020 (8.804.190). Usarla subestimaría la población en 253.219 personas.' + _NYC_OBS.format(id='xywu-7bv9'),
      'verificaciones.json'),
    F('F26', '2020 Neighborhood Tabulation Areas (NTAs)', 'NYC Department of City Planning (DCP)', 'Entidad pública', NYC + '9nt8-h7nd.geojson', 'GeoJSON', 'API sin llave',
      'no declara', 'No', '262 barrios de NYC', 'Geografía 2020', 'Trimestral', P, 'Integrada al lago',
      'Fuente oficial que reemplaza la copia no oficial de GitHub (veltman/snd3) que usaba el prototipo', 'Capa de referencia del mapa.' + _NYC_OBS.format(id='9nt8-h7nd'), 'geo/barrios_nta.geojson'),
    F('F27', 'Police Precincts', 'NYC Department of City Planning (DCP)', 'Entidad pública', NYC + 'y76i-bdw7.geojson', 'GeoJSON', 'API sin llave',
      'no declara', 'No', 'Precintos del NYPD', 'Vigente', 'Trimestral', P, 'Integrada al lago',
      'Fuente oficial que reemplaza la copia de GitHub (ResidentMario/geoplot-data) que usaba el prototipo', 'Capa de referencia del mapa.' + _NYC_OBS.format(id='y76i-bdw7'), 'geo/precintos.geojson'),
    F('F28', 'OpenFreeMap (teselas vectoriales de OpenStreetMap, con edificios 3D)', 'OpenFreeMap / OpenStreetMap contributors', 'Plataforma colaborativa', 'https://tiles.openfreemap.org/styles/liberty', 'Otro', 'API sin llave',
      'ODbL (datos OpenStreetMap) · © OpenMapTiles', 'No', 'Mundo', 'Vigente', 'Diaria', P, 'Integrada al lago',
      'Misma base cartográfica del Cerebro Lima', 'Mapa base y volúmenes 3D de edificios del gemelo; se carga en vivo, no se guarda.', '(en vivo, sitio web)'),
    F('F29', 'NYC Tourism + Conventions: informe anual 2025 (comunicado de prensa)', 'New York City Tourism + Conventions', 'Academia u ONG',
      'https://www.business.nyctourism.com/press-media/press-releases/NYC-Tourism-Annual-Report-March-2026', 'Página web', 'Solo PDF o página',
      'no declara', 'No', 'Ciudad de NY (total)', '2025', 'Anual', P, 'Integrada al lago',
      'Búsqueda web dirigida; la versión anterior usaba la cifra de 2024',
      'Cifra declarada, no verificable con microdatos: 65 M visitantes (52,4 M nacionales, 12,5 M internacionales), US$55.600 M de gasto directo y US$84.700 M de impacto. Se marca como «declarado» en el sitio.',
      '(sitio web, cifras declaradas)'),
    F('F30', 'NYC Council: aprobación del presupuesto FY2027 (comunicado)', 'New York City Council', 'Entidad pública', 'https://council.nyc.gov/press/2026/06/30/3166/', 'Página web', 'Solo PDF o página',
      'no declara', 'No', 'Ciudad de NY', 'Año fiscal 2027 (jul-2026 a jun-2027)', 'Anual', P, 'Integrada al lago',
      'Búsqueda web; la versión anterior citaba el presupuesto FY2026 (US$116.000 M), ya desactualizado',
      'US$125.800 M adoptados el 30-jun-2026. Cifra declarada. El detalle por agencia existe en PDF de la Oficina de Presupuesto (OMB) pero no como dato abierto tabular.',
      '(sitio web, cifras declaradas)'),
    F('F31', 'Esri World Imagery (teselas satelitales)', 'Esri', 'Empresa privada', 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer', 'Otro', 'API sin llave',
      'no declara', 'No', 'Mundo', 'Mosaico vigente (varias fechas)', 'No se sabe', P, 'Integrada al lago',
      'Misma capa satelital que usa el Cerebro Lima',
      'Solo capa visual opcional del gemelo; exige atribución a Esri y proveedores. No se descarga ni se analiza.', '(en vivo, sitio web)'),
    F('F32', 'DOB Permit Issuance (sistema legado BIS)', 'NYC Department of Buildings (DOB)', 'Entidad pública', NYC + 'ipu4-2q9a.json', 'JSON', 'API sin llave',
      'no declara', 'Personas identificables', 'Ciudad de NY', '1989 a hoy', 'Diaria', P, 'Descartada',
      'Claude Code la consultó para saber si el sistema legado seguía activo',
      'Permisos emitidos en el sistema legado. Sus fechas son texto MM/DD/AAAA: un filtro de fecha normal devuelve 0 filas sin avisar (ver Bitácora). Con filtro de texto aparecen 10.065 permisos en 2025, residuales frente a DOB NOW. Trae nombre y dirección del propietario y teléfono del contratista (permittee).' + _NYC_OBS.format(id='ipu4-2q9a'),
      'verificaciones.json'),
]
